<input type="hidden" id="thisAction" value="<?php echo $this->action; ?>" />
<div id="aclIndexAdd">
    <?php echo $this->translate('admin-acl-add:header'); ?>
	<br /><br />

    <?php if (isset($this->roleName)) : ?>
        <input type="hidden" id="roleNamePreset" value="true" />
    <?php endif; ?>
    <form method="post" id="aclEditor" action="" class="checkRequiredFields">
        <table class="form">
            <tbody>
            <tr>
                <td><label for="roleName"><?php echo $this->translate('admin-acl-form:roleName'); ?></label></td>
                <td><input type="text" class="required" name="roleName" id="roleName" value="<?php echo $this->roleName; ?>" size="30" maxlength="126" /></td>
            </tr>
            <tr>
                <td style="vertical-align:middle"><label for="inheritRoleId"><?php echo $this->translate('admin-acl-form:inheritFrom'); ?></label></td>
                <td>
                    <select name="inheritRoleId" id="inheritRoleId" class="required">
                        <?php foreach ($this->roles as $r => $value) : ?>
                        <option<?php echo ($r == $this->inheritRoleId) ? ' selected=selected' : ''; ?> value="<?php echo $r; ?>"><?php echo $value; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <button type="button" id="prePopulateButton"><?php echo (isset($this->roleName)) ? $this->translate('admin-acl-add:form:changeRole') : $this->translate('admin-acl-add:form:initializeRole'); ?></button>
                </td>
            </tr>
            </tbody>
        </table><br /><br />
        
        <?php if (isset($this->roleName)): ?>
        <div id="accessList">
            <?php foreach ($this->resources as $module => $controllers) : ?>
            <div class="aclSection">
                <table class="list">
                    <tbody>
                    <tr class="ui-widget-header">
                        <td width="300"><b><?php echo ucwords($module); ?></b></td>
                        <td width="120"><?php echo $this->translate('admin-acl-form:currently'); ?></td>
                        <td width="150"><?php echo $this->translate('admin-acl-form:grantRevoke'); ?></td>
                    </tr>
                    <?php foreach ($controllers as $controller => $actions) : ?>
                    <tr class="controller">
                        <td title="<?php echo $actions['description']; ?>" class="td1 description">
                        <?php echo ucwords($controller); ?>
                        </td>
                        <td class="<?php if (!empty($actions['all']['access'])) { echo 'access'; } else { if (!empty($actions['someaccess'])) { echo 'someAccess'; } else { echo 'noAccess'; }} ?>">
                        <?php if (!empty($actions['all']['access'])) : ?>
                            <?php echo $this->translate('admin-acl-form:allAccess'); ?>
                        <?php else: ?>
                            <?php if (isset($actions['someaccess'])) : ?>
                            <?php echo $this->translate('admin-acl-form:someAccess'); ?>
                            <?php else: ?>
                            <?php echo $this->translate('admin-acl-form:noAccess'); ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        </td>
                        <td>
                        <select size="1" class="allAccess" name="<?php echo $module . '[' . $controller . '][all]'; ?>" id="<?php echo $module . '_' . $controller; ?>">
                            <option value="<?php if (!empty($actions['all']['access'])) { echo 'allow'; } else { if (!empty($actions['someaccess'])) { echo 'some'; } else { echo 'deny'; }} ?>"><?php echo $this->translate('admin-acl-form:noChange'); ?></option>
                        <?php if (empty($actions['all']['access'])) : ?>
                            <option value="allow"><?php echo $this->translate('admin-acl-form:grantAllAccess'); ?></option>
                        <?php endif; ?>
                        <?php if (empty($actions['someaccess']) || !empty($actions['all']['access'])) : ?>
                            <option value="some"><?php echo (empty($actions['all']['access'])) ? $this->translate('admin-acl-form:grant') : $this->translate('admin-acl-form:revoke'); ?> <?php echo $this->translate('admin-acl-form:someAccess'); ?></option>
                        <?php endif; ?>
                        <?php if (!empty($actions['all']['access']) || !empty($actions['someaccess'])) : ?>
                            <option value="deny"><?php echo $this->translate('admin-acl-form:revokeAllAccess'); ?></option>
                        <?php endif; ?>
                        </select>
                        </td>
                    </tr>
                        <?php foreach ($actions['part'] as $action => $access) : ?>
                    <tr class="action <?php echo $module . '_' . $controller; ?>" style="display: <?php echo (empty($actions['someaccess']) || !empty($actions['all']['access'])) ? 'none' : ''; ?>;">
                        <td class="td1 description" title="<?php echo $access['description']; ?>">
                        <img src="<?php echo $this->baseUrl(); ?>/public/images/help.png" width="16" height="16" class="info" />
                        <?php echo ucwords($action); ?>
                        </td>
                        <td class="<?php echo (!empty($access['access'])) ? 'access' : 'noAccess'; ?>"><?php echo (!empty($access['access'])) ? $this->translate('admin-acl-form:hasAccess') : $this->translate('admin-acl-form:noAccess'); ?></td>
                        <td class="td3"><input type="checkbox" class="<?php echo $module . '_' . $controller; ?>_action" value="<?php echo (!empty($access['access'])) ? 'deny' : 'allow'; ?>" name="<?php echo $module . '[' . $controller . '][part][' . $action . ']'; ?>" id="<?php echo $module . '_' . $controller . '_part_' . $action; ?>" /> <?php echo (!empty($access['access'])) ? $this->translate('admin-acl-form:revokeAccess') : $this->translate('admin-acl-form:grantAccess'); ?></td>
                    </tr>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php endforeach; ?>
			<input type="submit" value="<?php echo $this->translate('admin-acl-form:submit'); ?>" />
        	<button type="button" id="cancel"><?php echo $this->translate('form-button-cancel'); ?></button>
        </div> 
        <?php endif; ?>       
    </form>
</div>