<?php echo $this->translate('admin-acl-delete:header', $this->role['name']); ?>
<br /><br />
<?php if ($this->accountRoleChange): ?>
<div class="ui-state-error ui-corner-all">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
        <?php echo $this->translate('admin-acl-delete:accountRoleChange', $this->defaultRole); ?>
    </p>
</div>
<br /><br />
<?php endif; ?>
<?php echo $this->translate('form-delete-confirm'); ?>
<?php echo $this->form; ?>