<div id="aclIndexDetails">
    <?php echo $this->translate('admin-acl-details:header', $this->role['name']); ?>
    <br /><br />
    <?php if ($this->acl['index']): ?>
        <a href="<?php echo $this->baseUrl(); ?>/admin/acl/" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('admin-acl-details:back'); ?><span class="ui-icon ui-icon-triangle-1-w"></span></a>
    <?php endif; ?>
    <?php if ($this->acl['edit'] && $this->role['editable']): ?>
        <a href="<?php echo $this->baseUrl(); ?>/admin/acl/edit/?roleId=<?php echo $this->role['roleId']; ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('admin-acl-details:edit'); ?><span class="ui-icon ui-icon-pencil"></span></a>
    <?php endif; ?>
    <?php if ($this->acl['delete'] && $this->role['editable']): ?>
        <a href="<?php echo $this->baseUrl(); ?>/admin/acl/delete/?roleId=<?php echo $this->role['roleId']; ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('admin-acl-details:delete'); ?><span class="ui-icon ui-icon-minusthick"></span></a>
    <?php endif; ?>
    <br /><br />
    <table class="form">
        <tbody>
	        <tr>
	            <td><label><?php echo $this->translate('admin-acl-form:roleName'); ?></label></td>
	            <td><?php echo $this->role['name']; ?></td>
	        </tr>
	        <tr>
	            <td><label><?php echo $this->translate('admin-acl-form:inheritFrom'); ?></label></td>
	            <td><?php echo ($this->role['inheritRoleId'] != 0) ? $this->inheritRole : $this->translate('admin-acl-form:noInheritance'); ?></td>
	        </tr>
	        <tr>
	            <td><label><?php echo $this->translate('admin-acl-details:editable') ?></label></td>
	            <td><?php echo ($this->role['editable'] == 1) ? $this->translate('form-button-yes') : $this->translate('form-button-no'); ?></td>
	        </tr>
        </tbody>
    </table>
    
        <div id="accessList">
        <h2><?php echo $this->translate('admin-acl-details:accessTitle'); ?></h2>
            <?php foreach ($this->resources as $module => $controllers) : ?>
            <div class="aclSection">
                <table class="list">
                    <tbody>
                    <tr class="ui-widget-header">
                        <td width="300"><b><?php echo ucwords($module); ?></b></td>
                        <td width="120"><?php echo $this->translate('admin-acl-details:form:access'); ?></td>
                    </tr>
                    <?php foreach ($controllers as $controller => $actions) : ?>
                    <tr class="controller">
                        <td title="<?php echo $actions['description']; ?>" class="td1 description">
                        <?php echo ucwords($controller); ?>
                        </td>
                        <td class="<?php if (!empty($actions['all']['access'])) { echo 'access'; } else { if (!empty($actions['someaccess'])) { echo 'someAccess'; } else { echo 'noAccess'; }} ?>">
                        <?php if (!empty($actions['all']['access'])) : ?>
                            <?php echo $this->translate('admin-acl-form:allAccess'); ?>
                        <?php else: ?>
                            <?php if (isset($actions['someaccess'])) : ?>
                            <?php echo $this->translate('admin-acl-form:someAccess'); ?>
                            <?php else: ?>
                            <?php echo $this->translate('admin-acl-form:noAccess'); ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        </td>
                    </tr>
                        <?php foreach ($actions['part'] as $action => $access) : ?>
                    <tr class="action <?php echo $module . '_' . $controller; ?>" style="display: <?php echo (empty($actions['someaccess']) || !empty($actions['all']['access'])) ? 'none' : ''; ?>;">
                        <td class="td1 description" title="<?php echo $access['description']; ?>">
                        <img src="<?php echo $this->baseUrl(); ?>/public/images/help.png" width="16" height="16" class="info" />
                        <?php echo ucwords($action); ?>
                        </td>
                        <td class="<?php echo (!empty($access['access'])) ? 'access' : 'noAccess'; ?>"><?php echo (!empty($access['access'])) ? $this->translate('admin-acl-form:hasAccess') : $this->translate('admin-acl-form:noAccess'); ?></td>
                    </tr>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php endforeach; ?>
        </div>    
</div>