
   
  
<?php if ($this->acl['add']): ?>
<a href="<?php echo $this->url(array('action' => 'add'), 'account', true); ?>" class="btn btn-success">
    <i class="icon-plus icon-white"></i>
<?php echo $this->translate('ot-account-all:linkNewAccount'); ?></a>
<br /><br />
<?php endif; ?>
<?php echo $this->translate('ot-account-all:header'); ?>
<br /><br />

<?php echo $this->form; ?>

<div class="results">
<?php if (count($this->paginator)): ?>

    <h4><?php echo $this->paginator->getTotalItemCount(); ?> User<?php echo ($this->paginator->getTotalItemCount() != 1) ? 's' : ''; ?> Found</h4>
    
    <table class="table table-striped table-bordered">    
        <thead>
            <tr>
                <th data-sort="name" data-direction="<?php echo ($this->sort == 'name') ? (($this->direction == 'asc') ? 'desc' : 'asc') : ''; ?>" class="<?php echo ($this->sort == 'name') ? $this->direction : ''; ?>">Name</th>                
                <th data-sort="username" data-direction="<?php echo ($this->sort == 'username') ? (($this->direction == 'asc') ? 'desc' : 'asc') : ''; ?>" class="<?php echo ($this->sort == 'username') ? $this->direction : ''; ?>">Username</th>
                <th>Login Method</th>           
            </tr>
        </thead>        
        <tbody>        
            <?php foreach ($this->paginator as $user): ?>    
                <tr>
                    <td><a href="<?php echo $this->url(array('accountId' => $user['accountId']), 'account', true); ?>"><?php echo $this->defaultVal($user['firstName'] . ' ' . $user['lastName'], 'Unknown'); ?></a></td>
                    <td><?php echo $user['username']; ?></td>
                    <td style="text-align:center">
                        <?php echo $this->adapters[$user['realm']]->name; ?>
                        <?php echo ($this->adapters[$user['realm']]->enabled == 0) ? ' (<b class="text-warning">DISABLED</b>)' : ''; ?>
                    </td>
                </tr>                
            <?php endforeach; ?>                    
        </tbody>    
    </table>
    
    <div id="itemFooter">
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'bootstrap-pagination.phtml', $this->filterOptions); ?>
    </div>
<?php else: ?>    
    <div class="noItems">No user accounts found.</div>    
<?php endif; ?>
</div>