
   
  
<?php if ($this->acl['add']): ?>
<a href="<?php echo $this->url(array('action' => 'add'), 'account', true); ?>" class="ui-state-default ui-corner-all linkButton">
<?php echo $this->translate('ot-account-all:linkNewAccount'); ?>
<span class="ui-icon ui-icon-plusthick"></span></a>
<br /><br />
<?php endif; ?>
<?php echo $this->translate('ot-account-all:header'); ?>
<br /><br />

<?php echo $this->form; ?>

<div class="results">
<?php if (count($this->paginator)): ?>

    <h4><?php echo $this->paginator->getTotalItemCount(); ?> User<?php echo ($this->paginator->getTotalItemCount() != 1) ? 's' : ''; ?> Found</h4>
    
    <table class="list">    
        <thead>
            <tr class="ui-widget-header">
                <th data-sort="name" data-direction="<?php echo ($this->sort == 'name') ? (($this->direction == 'asc') ? 'desc' : 'asc') : ''; ?>" class="<?php echo ($this->sort == 'name') ? $this->direction : ''; ?>">Name</th>                
                <th data-sort="username" data-direction="<?php echo ($this->sort == 'username') ? (($this->direction == 'asc') ? 'desc' : 'asc') : ''; ?>" class="<?php echo ($this->sort == 'username') ? $this->direction : ''; ?>">Username</th>
                <th>Login Method</th>
                <th>Actions</th>                
            </tr>
        </thead>        
        <tbody>        
            <?php foreach ($this->paginator as $user): ?>    
                <tr>
                    <td><?php echo $user['firstName'] . ' ' . $user['lastName']; ?></td>
                    <td><?php echo $user['username']; ?></td>
                    <td style="text-align:center">
                        <?php echo $this->adapters[$user['realm']]->name; ?>
                        <?php echo ($this->adapters[$user['realm']]->enabled == 0) ? ' (<b class="red">DISABLED</b>)' : ''; ?>
                    </td>
                    <td style="text-align:center"><a href="<?php echo $this->url(array('accountId' => $user['accountId']), 'account', true); ?>" class="ui-state-default ui-corner-all linkButtonNoText">Details</a></td>
                </tr>                
            <?php endforeach; ?>                    
        </tbody>    
    </table>
    
    <div id="itemFooter">
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'searchPaginationControl.phtml'); ?>
    </div>
<?php else: ?>    
   <div class="noItems">There are no requests at the moment.</div>    
<?php endif; ?>
</div>