
<textarea id="permissionList" style="display: none;"><?php echo $this->permissionList; ?></textarea>

<?php echo $this->translate('ot-account-edit:header'); ?>
<br /><br />

<div class="row">
    <div class="span6">
        <?php echo $this->form; ?>
    </div>
    <div class="span6">
        
    <?php if ($this->acl['edit-permission']): ?>
        <h3 id="permissionsHeader">Permissions for this user</h3>
        <p>
            Change the <b>Access Role</b> field to set the correct permissions.
        </p>
        <Br />
        <?php foreach ($this->permissions as $module => $controllers): ?>
            <h4><?php echo ucwords($module);?></h4>

            <div class="row">
                <?php foreach ($controllers as $controller => $actions) : ?>
                <div 
                    class="controller span1 <?php if (!empty($actions['all']['access'])) { echo 'access'; } else { if (!empty($actions['someAccess'])) { echo 'someAccess'; } else { echo 'noAccess'; }} ?>" 
                    id="<?php echo $module . '-' . $controller; ?>"
                    ><?php echo ucwords($controller); ?></div>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>

        <div style="clear:both;" />

        <?php foreach ($this->permissions as $module => $controllers) :?>
            <?php foreach ($controllers as $controller => $actions) : ?>
                    <?php if (isset($actions['part'])) :?>
                        <div id="wrapper-<?php echo $module . '-' . $controller ;?>" class="wrapper">
                            <div id="tooltip-<?php echo $module . '-' . $controller ;?>" class="actions">
                                <table class="list">
                                    <tr class="controller"><td><strong><?php echo ucwords($controller); ?></strong></td></tr>
                                    <?php foreach ($actions['part'] as $action => $access) :?>                        
                                        <tr><td class="action description <?php echo $access['access'] ? 'access' : 'noAccess';?>" id="<?php echo $module . '-' . $controller . '-' . $action;?>"><?php echo ucwords($action);?></td></tr>
                                    <?php endforeach;?>
                                </table>
                            </div>
                        </div>
                    <?php endif;?>
            <?php endforeach;?>
        <?php endforeach;?>
        
    <?php endif; ?>
        </div>
    </div>
</div>