<?php echo $this->translate('ot-account-edit:header'); ?>
<br /><br />
<?php echo $this->form; ?>

<?php foreach ($this->permissions as $module => $controllers): ?>
	<table class="<?php echo ucwords($module);?> list accessTable">
		<thead>
			<tr class="ui-widget-header">
				<td><?php echo ucwords($module);?></td>
			</tr>
		</thead>
		<tbody>
        	<?php foreach ($controllers as $controller => $actions) : ?>
            	<tr class="controller">
            		<td title="<?php echo $actions['description']; ?>" class="td1 description <?php if (!empty($actions['all']['access'])) { echo 'access'; } else { if (!empty($actions['someAccess'])) { echo 'someAccess'; } else { echo 'noAccess'; }} ?>">
                		<?php echo ucwords($controller); ?>
                	</td>
<!--                	<td style="/*margin : none; background : none; border : none;*/"></td>-->
            	</tr>
            	<?php if (isset($actions['part'])): ?>
            		<?php foreach ($actions['part'] as $action => $access) : ?>
          				<?php  if(empty($access['access'])) continue;?>
                		<tr class="action <?php echo $module . '_' . $controller; ?>">
                    		<td class="td1 description" title="<?php echo $access['description']; ?>">
<!--                    		<?php echo ucwords($action); ?>-->
                    		</td>
                    		<td title="<?php echo $access['description']; ?>" class="td1 description <?php echo (!empty($access['access'])) ? 'access' : 'noAccess'; ?>"><?php echo ucwords($action); ?></td>
                		</tr>
                	<?php endforeach; ?>
            	<?php endif; ?>
            <?php endforeach; ?>
		</tbody>
	</table>
<?php endforeach; ?>

<div style="clear:both;" />