<?php echo $this->translate('ot-account-index:header'); ?>
<br /><br />
<?php if ($this->acl['delete']): ?>
    <a href="<?php echo $this->url(array('action' => 'delete', 'accountId' => $this->userData['accountId']), 'account', true); ?>" class="ui-state-default ui-corner-all linkButton">
    <?php echo $this->translate('ot-account-index:linkDeleteUser'); ?>
    <span class="ui-icon ui-icon-minusthick"></span></a>
    <br /><br />
<?php endif; ?>

<div id="oauth">
    <ul>
        <li<?php echo ($this->tab == 'account') ? ' class="ui-tabs-selected"' : ''; ?>><a href="#tabs-data"><span><?php echo $this->translate('ot-account-index:account'); ?></span></a></li>
        <li<?php echo ($this->tab == 'apps') ? ' class="ui-tabs-selected"' : ''; ?>><a href="#tabs-apps"><span><?php echo $this->translate('ot-account-index:apps'); ?></span></a></li>
    </ul>
    <div id="tabs-data">
    <?php echo $this->translate('ot-account-index:userDataHeader'); ?>
    <br /><br />
    <?php if ($this->acl['edit'] || $this->acl['changePassword']) : ?>
        <?php if ($this->acl['edit']): ?>   
            
            <a href="<?php echo $this->url(array('action' => 'edit', 'accountId' => $this->userData['accountId']), 'account', true); ?>" class="ui-state-default ui-corner-all linkButton">
            <?php echo $this->translate('ot-account-index:linkEditUserData'); ?>
            <span class="ui-icon ui-icon-pencil"></span></a>
        <?php endif; ?>
        <?php if ($this->acl['changePassword']) : ?>
            <a href="<?php echo $this->url(array('action' => 'change-password'), 'account', true); ?>" class="ui-state-default ui-corner-all linkButton">
            <?php echo $this->translate('ot-account-index:linkChangePassword'); ?>
            <span class="ui-icon ui-icon-locked"></span></a>
        <?php endif; ?>
        <br /><br />        
    <?php endif; ?>    
        <div id="gravatarWrapper">
            <?php echo $this->gravatar($this->userData['emailAddress'], array('imgSize' => 128)); ?>
            <a href="http://gravatar.com" target="_blank">Change picture...</a>
        </div>
        <table class="form">
            <tbody>
                <tr>
                    <td width="130"><label><?php echo $this->translate('model-account-username'); ?></label></td>
                    <td><?php echo $this->userData['username']; ?></td>
                </tr>
                <tr>
                    <td><label><?php echo $this->translate('model-account-loginMethod'); ?></label></td>
                    <td><?php echo $this->userData['authAdapter']['name']; ?></td>
                </tr>
                <tr>
                    <td><label><?php echo $this->translate('model-account-role'); ?></label></td>
                    <td><?php echo implode(', ', $this->roles); ?></td>
                </tr>
                <tr>
                    <td>
                    <label><?php echo $this->translate('model-account-firstName'); ?></label></td>
                    <td><?php echo $this->userData['firstName']; ?></td>
                </tr> 
                <tr>
                    <td>
                    <label><?php echo $this->translate('model-account-lastName'); ?></label></td>
                    <td><?php echo $this->userData['lastName']; ?></td>
                </tr>                 
                <tr>
                    <td>            
                    <label><?php echo $this->translate('model-account-emailAddress'); ?></label></td>
                    <td><?php echo (empty($this->userData['emailAddress']) ? 'None' : $this->userData['emailAddress']); ?></td>
                </tr>                 
                <tr>
                    <td>            
                    <label><?php echo $this->translate('model-account-timezone'); ?></label></td>
                    <td><?php echo (empty($this->userData['timezone']) ? $this->config->user->timezone->val : $this->userData['timezone']); ?></td>
                </tr> 
                <?php foreach($this->attributes as $key=>$attr) : ?>
                <tr>
                    <td>            
                    <label><?php echo ucwords($key); ?>:</label></td>
                    <td>
                    <?php if (empty($attr)) : ?> 
                          <?php echo $this->translate('ot-account-index:none'); ?>
                    <?php elseif (is_array($attr)): ?>
                          <?php echo implode(', ', $attr); ?>
                    <?php else : ?>
                          <?php echo $attr; ?>
                    <?php endif; ?>
                    </td>
                </tr>         
                <?php endforeach; ?>
            </tbody>
        </table>
        * To change your account's picture, signup for an account at <a href="http://gravatar.com" target="_blank">Gravatar.com</a> and associate a picture with your account's email address (<?php echo $this->userData['emailAddress']; ?>).
    </div> 
    
    <div id="tabs-apps"> 
        <?php echo $this->translate('ot-account-index:apiapp-header'); ?>
        <br /><br />
        <a href="<?php echo $this->url(array('action' => 'api-docs'), 'apiapp', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('ot-account-index:viewApiDocumentation'); ?><span class="ui-icon ui-icon-gear"></span></a>
        <a href="<?php echo $this->url(array('action' => 'add'), 'apiapp', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('ot-account-index:apiapp-addButton'); ?><span class="ui-icon ui-icon-plusthick"></span></a>   
        <br /><br />
        <?php if (count($this->apiApps) != 0): ?>
            <?php foreach ($this->apiApps as $c): ?>
            <div class="consumer" style="background-image:url(<?php echo ($c['imageId'] != 0) ? $this->url(array('imageId' => $c['imageId']), 'image', true) : ''; ?>">
                
                <div class="options">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'appId' => $c['appId']), 'apiapp', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('ot-apiapp-details:appEditButton'); ?><span class="ui-icon ui-icon-pencil"></span></a>
                    <br /><br />
                    <a href="<?php echo $this->url(array('action' => 'delete', 'appId' => $c['appId']), 'apiapp', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('ot-apiapp-details:appDeleteButton'); ?><span class="ui-icon ui-icon-minusthick"></span></a>    
                    <br /><br />
                </div>
                
                <div class="details">    
                    <div class="name">
                        <?php echo $c['name']; ?>
                        <?php if ($c['website'] != ''): ?>
                            <span class="website">(<a target="_blank" href="<?php echo $c['website']; ?>"><?php echo $c['website']; ?></a>)</span>
                        <?php endif; ?>
                    </div>
                    <div class="description"><?php echo nl2br($c['description']); ?></div>                                                            
                    <div class="key"><b><?php echo $this->translate('ot-account-index:apiapp-apiKey'); ?>:</b> <?php echo $c['apiKey']; ?></div>
                </div>
                
                <div class="ui-helper-clearfix"></div>
            </div>
            <?php endforeach; ?>
        <?php else: ?>
        <?php echo $this->translate('ot-account-index:apiapp-noApplications'); ?>
        <?php endif; ?>           
        
    </div>
</div>
<br /><br />