<div id="adminSemesterIndex">
    These are the bugs which have been filed.<br /><br />

    <?php if ($this->acl['add']) : ?>
    <a href="<?php echo $this->baseUrl(); ?>/admin/bug/add/" class="ui-state-default ui-corner-all linkButton">New Bug Report<span class="ui-icon ui-icon-plusthick"></span></a>
    <br /><br />
    <?php endif; ?>
    <table class="list">
        <tbody>
	        <tr class="ui-widget-header">
	            <th width="250">Bug Title</th>
	            <th width="300">Submit Date/Time</th>
	            <th width="100">Status</th>
	        </tr>
	        <?php if (count($this->bugs) > 0) : ?>
	        <?php foreach ($this->bugs as $b) : ?>
	        <tr class="<?php $this->cycle('row1', 'row2'); ?>">
	            <td>
	            <?php if ($this->acl['details']) : ?>
	                <a href="<?php echo $this->baseUrl(); ?>/admin/bug/details/?bugId=<?php echo $b['bugId']; ?>"><?php echo $b['title']; ?></a>
	            <?php else: ?>
	                <?php echo $b['title']; ?>
	            <?php endif; ?>
	            </td>
	            <td style="text-align: center"><?php echo $this->dateFormat($b['submitDt'], $this->config->user->dateTimeFormat->val); ?> (<?php echo $this->elapsedTime($b['submitDt']); ?>)</td>
	            <td style="text-align: center"><?php echo ucwords($b['status']); ?></td>
	        </tr>
	       <?php endforeach; ?>
	       <?php else:  ?>
	        <tr>
	            <td colspan="3" class="noResults">No Bugs found</td>
	        </tr>
    	    <?php endif; ?>
	    </tbody>
    </table>
</div>