<?php echo $this->translate("login-index-login:header"); ?> 
<br /><br />
<form action="" method="post" id="login" class="checkRequiredFields">

<table class="form">
    <tbody>
    <tr>
        <td class="label"><label for="userId"><?php echo $this->translate("login-index-login:userId"); ?> </label></td>
        <td class="value"><input type="text" id="userId" name="userId" value="" class="required" /></td>
    </tr>
    <tr>
        <td class="label"><label for="password"><?php echo $this->translate("login-index-login:password"); ?> </label></td>
        <td class="value"><input type="password" id="password" name="password" class="required" /><br /><br />
        <a href="<?php echo $this->url(array('action' => 'forgot'), 'login', true); ?>"><?php echo $this->translate("login-index-login:clickHere"); ?></a> </td>
    </tr>
    </tbody>
</table>
<input type="submit" value="Login" />
</form>
<br /><br />
<form method="POST" action="<?php echo $this->url(array('action' => 'signup'), 'login', true); ?>" id="signup" class="checkRequiredFields">
<h3><?php echo $this->translate("login-index-login:noAccountTitle"); ?></h3>
<?php echo $this->translate("login-index-login:noAccountHeader"); ?>
<br /><br />
<table class="form">
    <tr>
        <td><label for="userId"><?php echo $this->translate("login-index-login:userId"); ?></label></td>
        <td><input type="text" id="userId" name="userId" value="" class="required" />
        <?php echo $this->translate("login-index-login:alphanumericOnly"); ?></td>
    </tr>
    <tr>
        <td><label for="email"><?php echo $this->translate("login-index-login:email"); ?></label></td>
        <td><input type="text" id="email" name="email" value="" class="required" /></td>
    </tr>
</table>
<input type="submit" value="<?php echo $this->translate("login-index-login:linkSignup"); ?>" />
</form>        