<div class="row">
    <div class="span8">
        <?php echo $this->translate("ot-login-signup:enterId"); ?>
        <br /><br />
        <?php echo $this->form; ?>
    </div>
    <div class="span4">
        <div class="">
            <h3>Have an account?</h3>
            <p>
                <?php echo $this->translate("ot-login-signup:header", $this->configVar('appTitle')); ?>
            </p>
            <br />
            <p>
                <a href="<?php echo $this->url(array('realm' => $this->realm), 'login', true); ?>" class="btn btn-danger"><?php echo $this->translate("ot-login-signup:clickHere"); ?></a>
            </p>
        </div>
    </div>
</div>

