<?php if (!$this->guestHasAccess) : ?>
    <div class="ui-widget ui-state-highlight ui-corner-all">
        <span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
        <?php echo $this->translate('ot-cron-index:noAccess', array($this->defaultRole->name))?>
        <?php if ($this->acl['acl']) : ?>
        <br />
        <a href="<?php echo $this->baseUrl(); ?>/ot/acl"><?php echo $this->translate('ot-cron-index:editAcl'); ?></a> 
        <?php endif; ?>
    </div>
    <br />
<?php endif; ?>

<?php echo $this->translate('ot-cron-index:header'); ?>
<br /><br />

    <?php if ($this->acl['toggle']): ?>
    <a href="<?php echo $this->url(array('controller' => 'cron', 'action' => 'toggle', 'name' => 'all', 'status' => 'diabled'), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('ot-cron-index:linkEnableAll'); ?><span class="ui-icon ui-icon-plusthick"></span></a>
    <a href="<?php echo $this->url(array('controller' => 'cron', 'action' => 'toggle', 'name' => 'all', 'status' => 'enabled'), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('ot-cron-index:linkDisableAll'); ?><span class="ui-icon ui-icon-minusthick"></span></a>  
    <br /><br />
    <?php endif; ?>

    <?php if (count($this->cronjobs) != 0): ?>
        <?php foreach ($this->cronjobs as $c): ?>
            <div class="job">
                <div class="status <?php echo (isset($this->status[$c->getName()]) && $this->status[$c->getName()]['status'] == 'enabled') ? 'enabled' : 'disabled'; ?>">&nbsp;</div>
                <div class="actions">
                    <?php if ($this->acl['toggle']): ?>
                        <a href="<?php echo $this->url(array('controller' => 'cron', 'action' => 'toggle', 'name' => $c->getName()), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton">
                            <?php
                            if (isset($this->status[$c->getName()]) && $this->status[$c->getName()]['status'] == 'enabled') {
                                echo $this->translate('ot-cron-index:disable') . '<span class="ui-icon ui-icon-minusthick"></span>';
                            } else {
                                echo $this->translate('ot-cron-index:enable') . '<span class="ui-icon ui-icon-plusthick"></span>';
                            }
                            ?>
                        </a>
                    <?php endif; ?>

                    <?php if (isset($this->status[$c->getName()]) && $this->status[$c->getName()]['status'] == 'enabled'): ?>
                        <a href="<?php echo $this->url(array('controller' => 'cron', 'action' => 'job', 'name' => $c->getName()), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('ot-cron-index:runNow'); ?><span class="ui-icon ui-icon-gear"></span></a>
                    <?php endif; ?>
                </div>
                <div class="name"><?php echo $c->getName(); ?></div>
                <div class="description"><?php echo $c->getDescription(); ?></div>
                <div class="schedule">
                    <?php
                    if (isset($this->status[$c->getName()]) && $this->status[$c->getName()]['lastRunDt'] != 0) {
                        echo 'Last executed ' . $this->elapsedTime($this->status[$c->getName()]['lastRunDt']);
                    } else {
                        echo $this->translate('ot-cron-index:neverRun');
                    }
                    ?>
                </div>
                <div class="ui-helper-clearfix"></div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
    <h3>No Cron Jobs Found</h3>
    <?php endif; ?>
