You can create a new account here.  A password will be created for you and sent to 
the email address you provide.  If you already have an account for <?php echo $this->config->user->appTitle->val; ?>, you can  
<a href="<?php echo $this->baseUrl(); ?>/login/?realm=<?php echo $this->realm; ?>">click here</a> to log in.<br /><br />
Enter your requested user ID below, as well as your email address.
<br /><br />
<div id="signupForm">
    <?php echo $this->form; ?>
</div>