<?php if (count($this->translationTable) != 0): ?>
<form method="post" id="translationForm" action="<?php echo $this->url(array('controller' => 'translate', 'action' => 'save'), 'ot', true); ?>">    
    <div class="accordion" id="accordion2">
        <?php $i = 0; foreach ($this->translationTable as $key => $value): ?>
        <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<?php echo $i; ?>">
                <?php echo $this->translate("ot-translate-index:section", $value['title']); ?>
              </a>
            </div>
            <div id="collapse<?php echo $i; ?>" class="accordion-body collapse">
              <div class="accordion-inner">
                <label for="<?php echo $key; ?>_old"><?php echo $this->translate("ot-translate-index:currentText"); ?></label><br />
                <textarea readonly="1" id="<?php echo $key; ?>_old" style="width:400px"><?php echo htmlentities($value['value']); ?></textarea>
                <br /><br />
                <label for="<?php echo $key; ?>_new"><?php echo $this->translate("ot-translate-index:changeText"); ?></label><br />
                <textarea style="width:400px" name="<?php echo $key; ?>" id="<?php echo $key; ?>_new"></textarea>
                <br /><br />
                <input type="checkbox" value="ON" name="<?php echo $key; ?>#reset" /> <?php echo $this->translate("ot-translate-index:removeText"); ?><br />
              </div>
            </div>
          </div>
        <?php $i++; endforeach; ?>
    </div>
</form>    
<?php else: ?>
<div class="alert">
<?php echo $this->translate("ot-translate-index:noChange"); ?>
</div>
<?php endif; ?>