<?php $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
<title><?php echo $this->config->user->appTitle->val; ?> - <?php echo $this->title; ?></title>
</head>
<body>
<h2>This application is currently in maintenance mode.  It should be back online shortly.</h2>
<br /><br />
<a href="<?php echo $this->url(array(), 'login', true); ?>">Administrators may log in here.</a>
</body>
</html>