<div>
    Enter in the information below to add custom attribute to this object.
    <br /><br />
    <form method="post" action="?objectId=<?php echo $this->objectId; ?>" id="add" class="checkRequiredFields">
	   <table class="form">
           <tbody>
	           <tr>
	               <td width="100"><label>Object:</label></td>
	               <td><?php echo $this->objectId; ?></td>
	           </tr>
	           <tr>
	               <td><label>Description:</label></td>
	               <td><?php echo $this->objectDescription; ?></td>
	           </tr>
            </tbody>
	    </table><br /><br />
	    <table class="form">
            <tbody>
    	        <tr>
    	            <td width="130"><label>Label:</label></td>
    	            <td><input type="text" name="label" id="label" value="" size="20" class="required" /></td>
    	        </tr>
    	        <tr>
    	            <td><label>Type:</label></td>
    	            <td>
                       <select name="type" class="required" id="type">
                            <?php foreach ($this->types as $type => $value) : ?>
                                <option value="<?php echo $value; ?>"><?php echo $type; ?></option>
                            <?php endforeach; ?>
                       </select>
    	               <div id="opt" style="display: none;">
    	                   <table class="form" id="options">
                               <tbody>
    		                      <tr id="optionRow">
    		                          <td width="50"><label for="option[]">Option:</label></td>
    		                          <td width="120"><input type="text" maxlength="128" size="20" name="option[]" value="" /></td>
    		                      </tr>
                              </tbody>
    		              </table>
    		            <a id="addRowButton" class="ui-state-default ui-corner-all linkButton"><span class="ui-icon ui-icon-plusthick"></span>Add Row</a>
    		            <a id="removeRowButton" class="ui-state-default ui-corner-all linkButton"><span class="ui-icon ui-icon-minusthick"></span>Remove Row</a>
    	               </div>
    	            </td>
    	        </tr>
    	        <tr>
    	            <td><label>Required:</label></td>
    	            <td><input type="checkbox" value="1" name="required" id="required" /></td>
    	        </tr>
                <tr>
                    <td><label>Display Direction:</label></td>
                    <td>
                        <label for="direction"><input type="radio" value="vertical" checked="checked" name="direction" /> Vertical</label>
                        <br />
                        <label for="direction"><input type="radio" value="horizontal" name="direction" /> Horizontal</label>
                    </td>
                </tr>
            </tbody>  
	    </table>
        <input type="submit" value="Add Custom Attribute" />
        <button type="button" id="cancel">Cancel</button>
    </form>
</div>