       <table class="form">
            <tbody>
	            <tr>
	                <td width="100"><label>Object:</label></td>
	                <td><?php echo $this->objectId; ?></td>
	            </tr>
	            <tr>
	                <td><label>Description:</label></td>
	                <td><?php echo $this->objectDescription; ?></td>
	            </tr>
            </tbody>
        </table>
        <br /><br />
        You have selected to delete the attribute <b><?php echo $this->attribute['label']; ?></b>.  Are you sure
        you want to do this?  <b>This will remove all data associated with this attribute.</b>
        <?php echo $this->form; ?>