<p>
    An API key is required to access the API.  You may sign up for a key
    from your <b><a href="<?php echo $this->url(array(), 'account', true); ?>">My Account</a></b>
    page.
</p>

<p>
    Your API key if required on every request.  You will append your key in the
    query string of your request.  For example, if you wanted to get the version
    information for this application you'd make a GET request  to <code><?php echo Zend_Registry::get('siteUrl'); ;?>/api/ot-version?key=[[yourApiKey]]</code>
</p>
<br />
<p>
    For POST, PUT, and DELETE methods, put all parameters (except your api key)
    as a URL encoded string in the post body of the request.
</p>
<a name="apitop"></a>
<br />

<div class="row">

    <?php if (count($this->endpoints) == 0): ?>
    <div class="span12">
        <div class="alert alert-warning">No API Methods available for your account.</div>
    </div>
    <?php else: ?>
    <div class="span9">
        <h3>API Methods Available For Your Account</h3>
    </div>
    <div class="span3 jump">
        <select id="jumpbox">
            <option value="">Jump to endpoint...</option>
            <?php foreach ($this->endpoints as $e): ?>
                <option><?php echo $e['name']; ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="span12">
        <?php foreach ($this->endpoints as $endpoint) : ?>
        <div class="well apiEndpoint">
            <a class="backToTop" href="#apitop">Back to top</a>
            <h4><a name="<?php echo $endpoint['name']; ?>"></a><?php echo Zend_Registry::get('siteUrl'); ;?>/api/<?php echo $endpoint['name']; ?></h4>
            <div class="endpointDescription">
                <?php echo $endpoint['description']; ?>
            </div>

            <?php foreach ($endpoint['methods'] as $method => $doc) : ?>
            <div class="method">
                <div class="protocol">
                    <b><?php echo strtoupper($method); ?> Request</b>
                </div>

                <div class="methodDescription"><?php echo $doc; ?></div>
            </div>

            <?php endforeach; ?>
        </div>

        <?php endforeach; ?>
    </div>
    <?php endif; ?>
</div>



