<p>
A key parameter is always required in the query string.  For example, if you
wanted to get the information for an account you'd make a GET request to the 
following URL:
</p>

<p>
<code style="background-color: #DDD; padding: 5px 25px;"><?php echo Zend_Registry::get('siteUrl'); ;?>/api/Ot_Account/accountId/[[accountId]]?key=[[yourApiKey]]</code>
</p>

<p>
    Below are all of the available endpoints for this application.
    <br /><br />
    For POST, PUT, and DELETE 
    methods, put all parameters (except the api key) as a URL encoded string in 
    the post body of the request.
</p>

<?php foreach ($this->endpoints as $endpoint => $methods) : ?>

<div class="apiEndpoint">
    <h2><?php echo $endpoint; ?></h2>
    <?php foreach ($methods as $method => $doc) : ?>

    <h3 class="httpMethod"><?php echo strtoupper($method); ?></h3>

    <div><pre><?php echo '    ' . trim($doc); ?></pre></div>

    <?php endforeach; ?>
</div>

<?php endforeach; ?>
