<?php
$auth = Zend_Auth::getInstance();

if (!$auth->hasIdentity()) {
    echo '<b>' . $this->translate('theme-scripts-auth:notLoggedIn') . '</b> ' . $this->translate('theme-scripts-auth:logInHere',array('<a href="' . $this->url(array(), 'login', true) . '" id="authLogin" class="authModal">', '</a>'));
} else {

    $identity = $auth->getIdentity();

    if (isset($identity->masquerading) && $identity->masquerading) {
        $identity = $identity->realAccount;
    }

    echo $this->translate('theme-scripts-auth:welcome') . ' ';

    echo '<a href="' . $this->url(array(), 'account', true) . '" id="authMyAccount">';

    echo $auth->getIdentity()->username;
   
    echo "</a>";

    echo ' &nbsp; | &nbsp; <a href="#logoutModal" data-toggle="modal">' . $this->translate('theme-scripts-auth:logOut') . '</a>';

    $identity = $auth->getIdentity();

    if (isset($identity->masquerading) && $identity->masquerading) {
        echo '<br /><span>You are masquerading as <a href="' . $this->url(array('action' => 'index', 'accountId' => $identity->accountId), 'account', true) . '">' . $identity->firstName . ' ' . $identity->lastName . '</a>. ' . '<a href="' . $this->url(array('action' => 'unmasquerade'), 'account', true) . '">Stop Masquerading</a></span>';
    }
}

$translate = Zend_Registry::get('Zend_Translate');
if (count($translate->getList()) > 1) {
    $list = $translate->getList();
    foreach ($list as &$l) {
        $l = Ot_Language::getLanguageName($l);
    }
    unset($l);

    echo '&nbsp; | &nbsp;';
    echo $this->formLabel('language_select', 'Language: ');
    echo $this->formSelect('language_select', $translate->getLocale(), null, $list);
}