<?php echo $this->doctype('XHTML1_STRICT'); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php

$this->headMeta()->appendName('keywords', $this->configVar('metaKeywords'))
                 ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                 ->appendHttpEquiv('Content-Language', 'en-US')
                 ->appendName('viewport', 'width=device-width, initial-scale=1.0');             

                 
echo $this->headMeta() . "\n";
$this->headTitle($this->configVar('appTitle'))
     ->headTitle(strip_tags($this->title))
     ->headTitle()->setSeparator(' - ');

echo "\n";

echo $this->headTitle() . "\n\n";

//print the minified (common) css first, then the autoloaded css
echo $this->minifyHeadLink() . "\n";
echo $this->headLink() . "\n\n";

// print the minified (common) scripts first, then the autoloaded scripts
echo $this->minifyHeadScript() . "\n";
echo $this->headScript() . "\n";
$this->overrideTranslation()->js(); 

echo "\n";
?>

</head>
<body>
    <input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl(); ?>" />

    <div class="navbar navbar-inverse navbar-fixed-top">

      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="<?php echo $this->baseUrl(); ?>"><?php echo $this->configVar('appTitle'); ?></a>
                    
          <div class="nav-collapse collapse">
              <p class="navbar-text pull-right">
                <?php echo $this->render('auth.phtml'); ?>
              </p>
              
              <?php echo $this->navigation()->menu()->setOnlyActiveBranch(false)->setRenderParents(false)->setPartial('bootstrap-nav.phtml'); ?>          
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

        <?php
            $zrMessages = array();
            $fmMessages = array();
            $mMessages = array();

            if (Zend_Registry::isRegistered('flashMessages')) {
                $zrMessages = Zend_Registry::get('flashMessages');
            }

            $mMessages = (isset($this->messages) && is_array($this->messages)) ? $this->messages : array();
            $messages = array_merge($zrMessages, $fmMessages, $mMessages);


            if (count($messages) > 0) {
                
                $sprites = array(
                    'error'   => 'error',
                    'info'    => 'info',
                    'warning' => 'block',
                    'success' => 'success',
                );
                
                if (count($messages) != 0) {
                    foreach ($messages as $m) {
                        $type = (is_object($m)) ? $m->type : 'info';
                        $message = (is_object($m)) ? $m->message : $m;
                        
                        echo '<div class="alert alert-' . (isset($sprites[$type]) ? $sprites[$type] : 'info') . '">'                        
                        . $this->translate($message)
                        . '</div>'
                        ;
                    }
                }
            }
            ?>
        
        <?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setMaxDepth(null)->setPartial('bootstrap-breadcrumbs.phtml'); ?>
        
        <h1><?php echo $this->title; ?></h1>
        <?php echo $this->layout()->content; ?>

    </div> <!-- /container -->    
</body>

<div id="authLogoutDialog" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Confirm Logout</h3>
  </div>
  <div class="modal-body">
    <?php echo $this->translate('theme-scripts-auth:sureLogOut'); ?>
  </div>
  <div class="modal-footer">
    <a href="<?php echo $this->url(array('action' => 'logout'), 'login', true); ?>" class="btn btn-primary">Yes, Log Out</a>
    <a href="#" class="btn btn" data-dismiss="modal" aria-hidden="true">Close</a>
  </div>
</div>
    
</html>

