This interface provides the ability to manage cron jobs.<br /><br />

    <?php if ($this->acl['add']): ?>
        <a href="<?php echo $this->baseUrl(); ?>/admin/cron/add/" class="ui-state-default ui-corner-all linkButton">Add New Cron Job<span class="ui-icon ui-icon-plusthick"></span></a>
    <?php endif; ?>
    
    <div id="alertWrapper">
    <div id="alertBox">CRON Job Ran Successfully</div>
    </div>

    <?php if ($this->acl['toggle']): ?>
    <a href="<?php echo $this->baseUrl(); ?>/admin/cron/toggle/?name=all&status=disabled" class="ui-state-default ui-corner-all linkButton">Enable All<span class="ui-icon ui-icon-plusthick"></span></a>
    <a href="<?php echo $this->baseUrl(); ?>/admin/cron/toggle/?name=all&status=enabled" class="ui-state-default ui-corner-all linkButton">Disable All<span class="ui-icon ui-icon-plusthick"></span></a>  
    <br /><br />
    <?php endif; ?>
    
    <table class="list">
        <tr class="ui-widget-header">
            <th width="175">Cron Job</th>
            <th width="130">Status</th>
            <th width="150">Execute</th>
            <th width="200">Last Run Date</th>
            <?php if ($this->acl['edit']): ?>
            <th width="50">Edit</th>
            <?php endif; ?>
        </tr>
        
        <?php if (count($this->cronjobs) > 0): ?>
        <?php foreach ($this->cronjobs  as $c): ?>
        <tr class="<?php $this->cycle('row1', 'row2'); ?>">
            <td><?php echo $c['name']; ?></td>
            <td style="text-align:center;" class="<?php echo $c['status']; ?>">
            <?php if ($this->acl['toggle']): ?>
            <a href="<?php echo $this->baseUrl(); ?>/admin/cron/toggle/?name=<?php echo $c['name']; ?>">
            <?php endif; ?>
            <?php if ($c['status'] == 'enabled'): ?>
            Enabled
            <?php else: ?>
            Disabled
            <?php endif; ?>
            <?php if ($this->acl['toggle']): ?>
            </a>
            <?php endif; ?>
            </td>
            <td style="text-align: center;">
            	<?php if ($c['status'] == 'enabled'): ?>
            		<a class="runLink" href="<?php echo $this->baseUrl(); ?>/cron/index/<?php echo $c['name']; ?>">Run Now</a>
                <?php else: ?>
                	Cannot run a disabled job
            	<?php endif; ?>
            </td>
            <td style="text-align: center;">
                <?php if ($c['lastRunDt'] == 0): ?>
                    Job has never run
                <?php else: ?>
                    <?php echo $this->elapsedTime($c['lastRunDt']); ?>
                <?php endif; ?>
            </td>
            <?php if ($this->acl['edit']): ?>
            <td style="text-align:center">
                <a href="<?php echo $this->baseUrl(); ?>/admin/cron/edit/?name=<?php echo $c['name']; ?>"><img src="<?php echo $this->baseUrl(); ?>/public/images/edit.png" alt="Edit" /></a>
            </td>
            <?php endif; ?>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td colspan="5" class="noResults">No Cron Jobs found</td>
        </tr>
        <?php endif; ?>
    </table>