<div class="ui-state-error ui-corner-all">
    <span class="ui-icon ui-icon-alert"></span>
    <?php if ($this->message == '') : ?>
        <?php echo $this->translate('default-index-error:noMessage'); ?>
    <?php else: ?>
        <?php echo $this->translate($this->message); ?>
    <?php endif; ?>
</div>
<br />
<?php if ($this->showTrackback) : ?>
<div id="trackback">
    <table class="list">
        <tbody>
            <tr>
                <th width="500"><?php echo $this->translate('default-index-error:file'); ?></th>
                <th width="150"><?php echo $this->translate('default-index-error:function'); ?></th>
                <th width="50"><?php echo $this->translate('default-index-error:line'); ?></th>
            </tr>
            <?php foreach($this->trackback as $t) : ?>
                <tr>
                    <td><?php echo (isset($t['file']) ? $t['file'] : 'N/A') ?></td>
                    <td><?php echo (isset($t['function']) ? $t['function'] : 'N/A') ?></td>
                    <td><?php echo (isset($t['line']) ? $t['line'] : 'N/A') ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <br />
</div>
<?php endif; ?>
    <input type="button" value="Back" id="cancel" />
<span id="error"></span>