<div class="errorBody ui-state-error">
    <div class="errorBox ui-corner-all">
        <h2 class="errorMessage gradient-red ui-corner-top<?php if (!$this->showTrackback) { echo ' ui-corner-bottom'; } ?>">
            <?php if ($this->message == '') : ?>
                <?php echo $this->translate('default-index-error:noMessage'); ?>
            <?php else: ?>
                <?php echo $this->translate($this->message); ?>
            <?php endif; ?>
            <input type="button" value="Go Back" id="cancel" />
        </h2>
        <?php if ($this->showTrackback) : ?>
            <div class="errorContent ui-corner-bottom ui-helper-clearfix">
                    <div id="trackback">
                        <table class="list errors">
                            <tbody>
                                <tr>
                                    <th width="500"><?php echo $this->translate('default-index-error:file'); ?></th>
                                    <th width="150"><?php echo $this->translate('default-index-error:function'); ?></th>
                                    <th width="50"><?php echo $this->translate('default-index-error:line'); ?></th>
                                </tr>
                                <?php foreach($this->trackback as $t) : ?>
                                    <tr class="<?php $this->cycle("row1","row2"); ?>">
                                        <td><?php echo (isset($t['file']) ? $t['file'] : 'N/A') ?></td>
                                        <td><?php echo (isset($t['function']) ? $t['function'] : 'N/A') ?></td>
                                        <td><?php echo (isset($t['line']) ? $t['line'] : 'N/A') ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<span id="error"></span>