<?php if ($this->acl['index']): ?>
<a href="<?php echo $this->baseUrl(); ?>/admin/emailqueue/" class="ui-state-default ui-corner-all linkButton">Back to Email List<span class="ui-icon ui-icon-triangle-1-w"></span></a>
<?php endif; ?>
<div id="adminemailDetails">
    <table class="form">
        <tbody>
	        <tr>
	            <td><label>Status:</label></td>
	            <td><a href="<?php echo $this->baseUrl(); ?>/admin/emailqueue/?status=<?php echo $this->email['status']; ?>"><?php echo ucwords($this->email['status']); ?></a></td>
	        </tr>
	        <tr>
	            <td><label>Queue Date:</label></td>
	            <td><?php echo $this->dateFormat($this->email['queueDt'], $this->config['dateTimeFormat']); ?></td>
	        </tr>
	        <tr>
	            <td><label>Sent Date:</label></td>
	            <td><?php echo ($this->email['status'] == 'sent') ? $this->formatDate($this->email['sentDt'], $this->config['dateTimeFormat']) : 'Not Sent'; ?></td>
	        </tr>
	        <tr>
	            <td><label>Affected Attribute:</label></td>
	            <td><a href="<?php echo $this->baseUrl(); ?>/admin/emailqueue/?attributeName=<?php echo $this->email['attributeName']; ?>&attributeId=<?php $this->email['attributeId']; ?>"><?php echo $this->email['attributeName']; ?> = <?php $this->email['attributeId']; ?></a></td>
	        </tr>
	        <tr>
	            <td><label>Call ID:</label></td>
	            <td><a href="<?php echo $this->baseUrl(); ?>/admin/emailqueue/?callId=<?php echo $this->email['callId']; ?>"><?php echo (!empty($this->email['callId'])) ? $this->email['callId'] : 'None'; ?></a></td>
	        </tr>
        </tbody>
    </table>
    <br /><br />
    <b>Message:</b><br /><br />
    <table class="form">
        <tbody>
	        <tr>
	            <td><label>To:</label></td>
	            <td><?php echo $this->email['msg']['to']; ?></td>
	        </tr>
	        <tr>
	            <td><label>From:</label></td>
	            <td><?php echo $this->email['msg']['from']; ?></td>
	        </tr>
	        <tr>
	            <td><label>Subject:</td>
	            <td><?php echo $this->email['msg']['subject']; ?></td>
	        </tr>
	        <tr>
	            <td><label>Body:</label></td>
	            <td><?php echo $this->email['msg']['body']; ?></td>
	        </tr>
        </tbody>
    </table>
</div>