<?php echo $this->doctype('XHTML1_STRICT'); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

<?php 

$this->headMeta()->appendName('keywords', $this->config->user->metaKeywords->val)
                 ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                 ->appendHttpEquiv('Content-Language', 'en-US');
                 
echo $this->headMeta();

$this->headTitle($this->config->user->appTitle->val)
     ->headTitle(strip_tags($this->title))
     ->headTitle()->setSeparator(' - ');
     
echo $this->headTitle();
?>

<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl(); ?>/public/ot/css/Ot/reset-fonts-grids.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl(); ?>/public/ot/css/Ot/base.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl(); ?>/public/css/layout.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl(); ?>/public/ot/css/superfish.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl(); ?>/public/ot/css/superfish-vertical.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl(); ?>/public/css/nav.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl(); ?>/public/ot/css/Ot/common.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl(); ?>/public/ot/themes/base/ui.all.css" />
<?php echo $this->headLink(); ?>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl(); ?>/public/css/overrides.css" />

<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/ot/scripts/jquery-1.3.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/ot/scripts/ui/minified/jquery.ui.all.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/ot/scripts/jquery.plugin.hoverIntent.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/ot/scripts/jquery.plugin.supersubs.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/ot/scripts/jquery.plugin.superfish.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/public/scripts/global.js"></script>
<?php $this->overrideTranslation()->js(); ?>
<?php echo $this->headScript(); ?>
</head>
<body>
    <input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl(); ?>" />

    <div id="doc4" class="yui-t7">
        <div id="hd" class="ui-corner-top">
            <div class="authInfo"><?php echo $this->render('auth.phtml'); ?></div>
            <span id="appTitle"><?php echo $this->config->user->appTitle->val; ?></span>
        </div>
        <div id="bd">
            <div class="yui-g" id="navBar">
                <?php echo $this->render('nav.phtml'); ?>
            </div>
            
            <div class="yui-g">
                <div class="content">
                    <?php if (!empty($this->messages) != 0) : ?>
                        <div id="systemMessages" class="ui-state-highlight ui-corner-all">
                            <span class="ui-icon ui-icon-info"></span>
                                <?php foreach ($this->messages as $m) : ?>
                                    <?php echo $this->translate($m); ?><br />
                                <?php endforeach; ?>
                        </div>
                   <?php endif; ?>

                    <div id="pageTitle"><?php echo $this->title; ?></div>

                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
            <?php $this->overrideTranslation()->link('Edit Text For This Page'); ?>
        </div>
        <div id="ft" class="ui-corner-bottom">
            <?php echo $this->render('footer.phtml'); ?>
        </div>
    </div>
    
</body>
</html>