<?php echo $this->translate('oauth-index-allConsumers:header', $this->config->user->appTitle->val); ?>
<br /><br />
<?php if (count($this->allConsumers) != 0): ?>
    <?php echo $this->translate('oauth-index-allConsumers:applicationListText'); ?>
    <br />
    <?php foreach ($this->allConsumers as $c): ?>
    <div class="consumer">
        <div class="options">
            <a href="<?php echo $this->baseUrl(); ?>/oauth/index/details/?consumerId=<?php echo $c['consumerId']; ?>&all=true" class="ui-state-default ui-corner-all linkButton">
                <?php echo $this->translate('oauth-index-allConsumers:detailsButton'); ?>
            <span class="ui-icon ui-icon-triangle-1-e"></span></a>          
        </div>      
        <div class="consumerIcon">
            <?php if ($c['imageId'] != 0): ?>
            <img src="<?php echo $this->baseUrl(); ?>/image/?imageId=<?php echo $c['imageId']; ?>" />
            <?php else: ?>
            <img src="<?php echo $this->baseUrl(); ?>/ot/images/consumer.png" alt="consumer" />
            <?php endif; ?>
        </div>  
        <div class="details">   
            <div class="name"><?php echo $c['name']; ?></div>
            <?php if ($c['website'] != ''): ?>
            <div class="website"><a target="_blank" class="linkButton" href="<?php echo $c['website']; ?>"><?php echo $c['website']; ?><span class="ui-icon ui-icon-extlink"></span></a></div>
            <?php endif; ?>
            <div class="description"><?php echo nl2br($c['description']); ?></div>
        </div>
    </div>
    <?php endforeach; ?>
<?php else: ?>
<?php echo $this->translate('oauth-index-allConsumers:noApplications'); ?>
<?php endif; ?>
