<?php if ($this->all) : ?>
<a href="<?php echo $this->url(array('action' => 'all-consumers'), 'oauth'); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('oauth-index-details:back'); ?><span class="ui-icon ui-icon-triangle-1-w"></span></a>
<?php else : ?>
<a href="<?php echo $this->url(array(), 'oauth'); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('oauth-index-details:back'); ?><span class="ui-icon ui-icon-triangle-1-w"></span></a>
<?php endif ;?>
<br /><br />
<div class="consumerIcon">
	<?php if ($this->consumer->imageId != 0): ?>
	<img src="<?php echo $this->url(array('imageId' => $this->consumer->imageId), 'image'); ?>" />
	<?php else: ?>
	<img src="<?php echo $this->baseUrl(); ?>/images/ot/consumer.png" alt="consumer" />
	<?php endif; ?>
</div>
<div class="consumer">
	<div class="name"><?php echo $this->consumer->name; ?></div>
	<?php if ($this->consumer->website != ''): ?>
	<div class="website"><a href="<?php echo $this->consumer->website; ?>"><?php echo $this->consumer->website; ?></a></div>
	<?php endif; ?>
	<div class="description"><?php echo nl2br($this->consumer->description); ?></div>
	<div class="usage"><?php echo $this->usage; ?> Active User<?php if ($this->usage != 1) { echo "s"; } ?></div>
</div>
<div class="ui-helper-clearfix"></div>
<div class="options">
	<a href="<?php echo $this->url(array('action' => 'regenerate-consumer-keys', 'consumerId' => $this->consumer->consumerId), 'oauth'); ?>" class="ui-state-default ui-corner-all linkButton">
	    <?php echo $this->translate('oauth-index-details:consumerRegenerateButton'); ?>
	<span class="ui-icon ui-icon-refresh"></span></a>
	<a href="<?php echo $this->url(array('action' => 'generate-token', 'consumerId' => $this->consumer->consumerId), 'oauth'); ?>" class="ui-state-default ui-corner-all linkButton">
	    <?php echo $this->translate('oauth-index-details:generateTokenButton'); ?>
	<span class="ui-icon ui-icon-plusthick"></span></a>		
	<a href="<?php echo $this->url(array('action' => 'delete', 'consumerId' => $this->consumer->consumerId), 'oauth'); ?>" class="ui-state-default ui-corner-all linkButton">
	    <?php echo $this->translate('oauth-index-details:consumerDeleteButton'); ?>
	<span class="ui-icon ui-icon-minusthick"></span></a>	
	<a href="<?php echo $this->url(array('action' => 'edit', 'consumerId' => $this->consumer->consumerId), 'oauth'); ?>" class="ui-state-default ui-corner-all linkButton">
	    <?php echo $this->translate('oauth-index-details:consumerEditButton'); ?>
	<span class="ui-icon ui-icon-pencil"></span></a>
</div>	

<?php if ($this->consumer->callbackUrl != ''): ?>
<div class="access"><?php echo $this->translate('oauth-index-details:callbackUrl'); ?></div>
<div class="key"><?php echo $this->consumer->callbackUrl; ?></div>
<?php endif; ?>
<div class="access"><?php echo $this->translate('oauth-index-details:consumerKey'); ?></div>
<div class="key"><?php echo $this->consumer->consumerKey; ?></div>

<div class="access"><?php echo $this->translate('oauth-index-details:consumerSecret'); ?></div>
<div class="key"><?php echo $this->consumer->consumerSecret; ?></div>

<div class="access"><?php echo $this->translate('oauth-index-details:requestTokenUrl'); ?></div>
<div class="key"><?php echo Zend_Registry::get('siteUrl'); ?>/oauth/server/request-token</div>

<div class="access"><?php echo $this->translate('oauth-index-details:accessTokenUrl'); ?></div>
<div class="key"><?php echo Zend_Registry::get('siteUrl'); ?>/oauth/server/access-token</div>

<div class="access"><?php echo $this->translate('oauth-index-details:authorizeUrl'); ?></div>
<div class="key"><?php echo Zend_Registry::get('siteUrl'); ?>/oauth/server/authorize</div>

<div id="signature"><?php echo $this->translate('oauth-index-details:encryptionNotice'); ?></div>
