<?php echo $this->translate('ot-activeusers-index:header'); ?>
<br /><br />
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Username</th>
            <th>Name</th>
            <th>Email Address</th>
            <th>Last Activity</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->activeUsers as $a) : ?>
        <tr class="<?php echo $this->cycle('row1', 'row2'); ?>">
            <td><a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'index', 'accountId' => $a['accountInfo']->accountId), 'ot', true); ?>"><?php echo $a['accountInfo']->username; ?></a></td>
            <td><?php echo $a['accountInfo']->firstName; ?> <?php echo $a['accountInfo']->lastName; ?></td>
            <td><?php echo $a['accountInfo']->emailAddress; ?></td>
            <td><?php echo $this->elapsedTime($a['dt']); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>