<?php echo $this->doctype('XHTML1_STRICT'); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php 
$this->headMeta()->appendName('keywords', $this->config->user->metaKeywords->val)
                 ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                 ->appendHttpEquiv('Content-Language', 'en-US');             
                 
echo $this->headMeta() . "\n";
$this->headTitle($this->config->user->appTitle->val)
     ->headTitle(strip_tags($this->title))
     ->headTitle()->setSeparator(' - ');

echo "\n";
     
echo $this->headTitle() . "\n\n";

//print the minified (common) css first, then the autoloaded css
echo $this->minifyHeadLink() . "\n";
echo $this->headLink() . "\n\n";

// print the minified (common) scripts first, then the autoloaded scripts
echo $this->minifyHeadScript() . "\n";
echo $this->headScript() . "\n";
$this->overrideTranslation()->js(); 

echo "\n";
?>

</head>
<body>
    <input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl(); ?>" />

    <div id="doc4" class="yui-t7">
        <div id="hd" class="ui-widget-header ui-corner-top">
            <div class="authInfo"><?php echo $this->render('auth.phtml'); ?></div>
            <span id="appTitle"><?php echo $this->config->user->appTitle->val; ?></span>
        </div>
        <div id="bd">
            <div class="yui-g" id="navBar">
                <?php echo $this->render('nav.phtml'); ?>
            </div>
            
            <div class="yui-g">
                <div class="content">
                    <?php if (!empty($this->messages) != 0) : ?>
                        <div id="systemMessages" class="ui-state-highlight ui-corner-all">
                            <span class="ui-icon ui-icon-info"></span>
                                <?php foreach ($this->messages as $m) : ?>
                                    <?php echo $this->translate($m); ?><br />
                                <?php endforeach; ?>
                        </div>
                   <?php endif; ?>

                    <div id="pageTitle"><?php echo $this->title; ?></div>

                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
            <?php $this->overrideTranslation()->link($this->translate('theme-layouts-layout:editText')); ?>
        </div>
        <div id="ft" class="ui-corner-bottom">
            <?php echo $this->render('footer.phtml'); ?>
        </div>
    </div>
    
</body>
</html>