<a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'details', 'key' => $this->host->getKey()), 'ot', true); ?>"><i class="icon icon-arrow-left"></i> <?php echo $this->translate("ot-custom-add:linkBack", $this->host->getName()); ?></a>
<Br /><Br />

<?php echo $this->translate("ot-custom-add:header", array($this->fieldType->getName(), $this->host->getName())); ?>
<br /><br />
<?php echo $this->form; ?>