<div>
    <?php echo $this->translate("admin-custom-add:header"); ?>
    <br /><br />
    <form method="post" action="" id="add" class="checkRequiredFields">
	   <table class="form">
           <tbody>
	           <tr>
	               <td width="100"><label><?php echo $this->translate("admin-custom-form:object"); ?></label></td>
	               <td><?php echo $this->objectId; ?></td>
	           </tr>
	           <tr>
	               <td><label><?php echo $this->translate("admin-custom-form:description"); ?></label></td>
	               <td><?php echo $this->objectDescription; ?></td>
	           </tr>
            </tbody>
	    </table><br /><br />
	    <table class="form">
            <tbody>
    	        <tr>
    	            <td width="130"><label><?php echo $this->translate("admin-custom-form:label"); ?></label></td>
    	            <td><input type="text" name="label" id="label" value="" size="20" class="required" /></td>
    	        </tr>
    	        <tr>
    	            <td><label><?php echo $this->translate("admin-custom-form:type"); ?></label></td>
    	            <td>
                       <select name="type" class="required" id="type">
                            <?php foreach ($this->types as $type => $value) : ?>
                                <option value="<?php echo $value; ?>"><?php echo $type; ?></option>
                            <?php endforeach; ?>
                       </select>
    	               <div id="opt" style="display: none;">
    	                   <table class="form" id="options">
                               <tbody>
    		                      <tr id="optionRow">
    		                          <td width="50"><label for="option[]"><?php echo $this->translate("admin-custom-form:option"); ?></label></td>
    		                          <td width="120"><input type="text" maxlength="128" size="20" name="option[]" value="" /></td>
    		                      </tr>
                              </tbody>
    		              </table>
    		            <a id="addRowButton" class="ui-state-default ui-corner-all linkButton"><span class="ui-icon ui-icon-plusthick"></span><?php echo $this->translate("admin-custom-form:linkAddRow"); ?></a>
    		            <a id="removeRowButton" class="ui-state-default ui-corner-all linkButton"><span class="ui-icon ui-icon-minusthick"></span><?php echo $this->translate("admin-custom-form:linkRemoveRow"); ?></a>
    	               </div>
    	            </td>
    	        </tr>
    	        <tr>
    	            <td><label><?php echo $this->translate("admin-custom-form:required"); ?></label></td>
    	            <td><input type="checkbox" value="1" name="required" id="required" /></td>
    	        </tr>
                <tr>
                    <td><label><?php echo $this->translate("admin-custom-form:direction"); ?></label></td>
                    <td>
                        <label for="direction"><input type="radio" value="vertical" checked="checked" name="direction" /> <?php echo $this->translate("admin-custom-form:vertical"); ?></label>
                        <br />
                        <label for="direction"><input type="radio" value="horizontal" name="direction" /> <?php echo $this->translate("admin-custom-form:horizontal"); ?></label>
                    </td>
                </tr>
            </tbody>  
	    </table>
        <input type="submit" value="<?php echo $this->translate("admin-custom-add:linkAdd"); ?>" />
        <button type="button" id="cancel"><?php echo $this->translate("form-button-cancel"); ?></button>
    </form>
</div>