<div>
    <?php if ($this->acl['edit']) : ?>
       <a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'edit', 'attributeId' => $this->attribute['attributeId']), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate("form-button-edit"); ?><span class="ui-icon ui-icon-pencil"></span></a>
    <?php endif; ?>
    <?php if ($this->acl['delete']) : ?>
       <a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'delete', 'attributeId' => $this->attribute['attributeId']), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate("ot-custom-attributeDetails:delete"); ?><span class="ui-icon ui-icon-minusthick"></span></a>
    <?php endif; ?>
    <br /><br />
    <table class="form">
        <tbody>
	        <tr>
	            <td width="100"><label><?php echo $this->translate("ot-custom-form:object"); ?></label></td>
	            <td><?php echo $this->objectId; ?></td>
	        </tr>
	        <tr>
	            <td><label><?php echo $this->translate("ot-custom-form:description"); ?></label></td>
	            <td><?php echo $this->objectDescription; ?></td>
	        </tr>
        </tbody>
    </table>
    <br /><br />
    <table class="form">
        <tbody>
	        <tr>
	            <td width="130"><label><?php echo $this->translate("ot-custom-form:label"); ?></label></td>
	            <td><?php echo $this->attribute['label']; ?></td>
	        </tr>
	        <tr>
	            <td><label><?php echo $this->translate("ot-custom-form:type"); ?></label></td>
	            <td><?php echo $this->attribute['type']; ?></td>
	        </tr>
	        <tr>
	            <td><label><?php echo $this->translate("ot-custom-form:required"); ?></label></td>
	            <td><?php echo (!empty($this->attribute['required'])) ? $this->translate("form-button-yes") : $this->translate("form-button-no"); ?></td>
	        </tr>
	        <tr>
	            <td><label><?php echo $this->translate("ot-custom-form:direction"); ?></label></td>
	            <td><?php echo ucwords($this->attribute['direction']); ?></td>
	        </tr>
	        <?php if ($this->attribute['type'] == 'radio' || $this->attribute['type'] == 'select') : ?>
	        <tr>
	            <td><label><?php echo $this->translate("ot-custom-attributeDetails:options"); ?></label></td>
	            <td>
                <?php if (count($this->attribute['options']) > 0) : ?>
    	            <?php foreach ($this->attribute['options'] as $option) : ?>
    	                <?php echo $option; ?><br />
    	            <?php endforeach; ?>
                <?php else : ?>
                    <?php echo $this->translate("ot-custom-attributeDetails:noOptions"); ?>
	            <?php endif; ?>
	            </td>
	        </tr>
	        <?php endif; ?>
        </tbody>
    </table>
</div>