<a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'index'), 'ot', true); ?>"><i class="icon icon-arrow-left"></i> <?php echo $this->translate("ot-custom-details:linkBack"); ?></a>
<br /><br />

<div class="row">
    <div class="span4">
        <div class="thumbnail">
            <table class="form">
                <tbody>
                    <tr>
                        <td width="100"><label><?php echo $this->translate("ot-custom-form:object"); ?></label></td>
                        <td><?php echo $this->object->getName(); ?></td>
                    </tr>
                    <tr>
                        <td><label>Key:</label></td>
                        <td><?php echo $this->object->getKey(); ?></td>
                    </tr>
                    <tr>
                        <td><label><?php echo $this->translate("ot-custom-form:description"); ?></label></td>
                        <td><?php echo $this->object->getDescription(); ?></td>
                    </tr>
                </tbody>
            </table>
            <p>             
            </p>
        </div>
    </div>
    <div class="span8">
           
        <?php if ($this->acl['add']) : ?>
        <a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'add', 'key' => $this->object->getKey()), 'ot', true); ?>" class="btn btn-success"><i class="icon-white icon-plus"></i> <?php echo $this->translate("ot-custom-details:linkAdd"); ?></a>
        <?php endif; ?>
        
        <input id="objectId" type="hidden" value="<?php echo $this->object->getKey(); ?>" />
        <?php if (count($this->attributes) > 0) : ?>
            <ul id="attributeList" class="ui-sortable">
                <?php foreach ($this->attributes as $a) : ?>
                    <li id="attribute_<?php echo $a['attributeId']; ?>">
                        <div class="well">
                            <div class="row">
                                <div class="span4">
                                    <i class="icon icon-resize-vertical"></i>  
                                    <?php if ($this->acl['attributeDetails']) : ?>
                                        <a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'attribute-details', 'attributeId' => $a['attributeId']), 'ot', true); ?>"><?php echo $this->truncate($a['label'], 50); ?></a>
                                    <?php else : ?>
                                        <?php echo $this->truncate($a['label'], 50); ?>
                                    <?php endif;  ?>
                                    (<?php echo $a['type']; ?>)
                                </div>
                                <div class="span3 pull-right actions">
                                    <?php if ($this->acl['edit']) : ?>
                                        <a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'edit', 'attributeId' => $a['attributeId']), 'ot', true); ?>" class="btn"><i class="icon icon-pencil"></i> Edit</a>
                                    <?php endif; ?>&nbsp;
                                    <?php if ($this->acl['delete']) : ?>
                                        <a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'delete', 'attributeId' => $a['attributeId']), 'ot', true); ?>" class="btn btn-danger"><i class="icon-white icon-ban-circle"></i> Delete</a>
                                    <?php endif; ?>                                    
                                </div>
                            </div>
                        </div>
                        <?php if ($this->acl['delete']) : ?>
                        
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else : ?>
            <?php echo $this->translate("ot-custom-details:noAttributes"); ?>
        <?php endif; ?>
    </div>
</div>


    
