<?php echo $this->translate("ot-custom-index:header"); ?>
<br /><br />
<?php if (count($this->hosts) > 0) : ?>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th class="span4"><?php echo $this->translate("ot-custom-index:table:object"); ?></th>
            <th><?php echo $this->translate("ot-custom-index:table:description"); ?></th>
        </tr>
    </thead>
    <tbody>
        
        <?php foreach ($this->hosts as $h) : ?>
        <tr>
            <td><a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'details', 'key' => $h->getKey()), 'ot', true); ?>"><?php echo $h->getName(); ?> (<?php echo $h->getKey(); ?>)</a></td>
            <td><?php echo $h->getDescription(); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else : ?>
<?php echo $this->translate("ot-custom-index:noObjects"); ?>
<?php endif; ?>