<?php echo $this->translate("ot-custom-index:header"); ?>
<br /><br />
<?php if (count($this->objects) > 0) : ?>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th class="span4"><?php echo $this->translate("ot-custom-index:table:object"); ?></th>
            <th><?php echo $this->translate("ot-custom-index:table:description"); ?></th>
        </tr>
    </thead>
    <tbody>
        
        <?php foreach ($this->objects as $o) : ?>
        <tr>
            <td><a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'details', 'key' => $o->getKey()), 'ot', true); ?>"><?php echo $o->getName(); ?> (<?php echo $o->getKey(); ?>)</a></td>
            <td><?php echo $o->getDescription(); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else : ?>
<?php echo $this->translate("ot-custom-index:noObjects"); ?>
<?php endif; ?>