<?php echo $this->translate("ot-custom-index:header"); ?>
<br /><br />

<table class="list">
    <tbody>
        <tr class="ui-widget-header">
            <th width="200"><?php echo $this->translate("ot-custom-index:table:object"); ?></th>
            <th width="350"><?php echo $this->translate("ot-custom-index:table:description"); ?></th>
        </tr>
        <?php if (count($this->objects) > 0) : ?>
	    <?php foreach ($this->objects as $o) : ?>
	    <tr class="<?php $this->cycle('row1', 'row2'); ?>">
	        <td><a href="<?php echo $this->url(array('controller' => 'custom', 'action' => 'details', 'objectId' => $o['objectId']), 'ot', true); ?>"><?php echo $o['objectId']; ?></a></td>
	        <td><?php echo $o['description']; ?></td>
	    </tr>
	    <?php endforeach; ?>
        <?php else : ?>
	    <tr>
	        <td colspan="2" class="noResults"><?php echo $this->translate("ot-custom-index:noObjects"); ?></td>
	    </tr>
        <?php endif; ?>
    </tbody>
</table>