<?php echo $this->translate("ot-trigger-add:header"); ?>
<?php echo $this->form; ?>
<?php echo $this->translate("ot-trigger-availableTitle"); ?>
<br /><br />
<?php echo $this->translate("ot-trigger-availableHeader"); ?>
<br /><br />
<table class="list">
    <tbody>
        <tr class="ui-widget-header">
            <th width="200"><?php echo $this->translate("ot-trigger-table:variable"); ?></th>
            <th width="300"><?php echo $this->translate("ot-trigger-table:description"); ?></th>
        </tr>
        <?php if (count($this->templateVars) > 0) : ?>
            <?php foreach ($this->templateVars as $key => $variable) : ?>
            <tr>
                <td>[[<?php echo $key; ?>]]</td>
                <td><?php echo $variable; ?></td>
            </tr>
            <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td colspan="2"><?php echo $this->translate("ot-trigger-add:noVariables"); ?></td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>