<?php if (!$this->clonedTriggerName) : ?>
    <?php echo $this->translate("ot-trigger-add:header"); ?>
<?php else : ?>
    <?php echo $this->translate("ot-trigger-add:cloneHeader", array('triggerName' => $this->clonedTriggerName)); ?>
<?php endif; ?>
<br /><br />

<div class="row">
    <div class="span8">        
        <?php echo $this->form; ?>
    </div>
    <div class="span4">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th><?php echo $this->translate("ot-trigger-table:variable"); ?></th>
                    <th><?php echo $this->translate("ot-trigger-table:description"); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php if (count($this->trigger->getOptions()) > 0) : ?>
                    <?php foreach ($this->trigger->getOptions() as $key => $variable) : ?>
                    <tr>
                        <td>[[<?php echo $key; ?>]]</td>
                        <td><?php echo $variable; ?></td>
                    </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                <tr>
                    <td colspan="2"><?php echo $this->translate("ot-trigger-add:noVariables"); ?></td>
                </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
<?php echo $this->translate("ot-trigger-availableTitle"); ?>
<br /><br />
<?php echo $this->translate("ot-trigger-availableHeader"); ?>
<br /><br />
