<a href="<?php echo $this->url(array('controller' => 'trigger'), 'ot', true); ?>"><i class="icon icon-arrow-left"></i> <?php echo $this->translate("ot-trigger-details:linkBack"); ?></a><br /><br />

<div class="row">
    <div class="span4">
        <div class="thumbnail">
            <h4><?php echo $this->trigger->getName(); ?></h4>
            <p>
                <?php echo $this->trigger->getDescription(); ?>
            </p>
            <br />
            <p>
                <?php if ($this->acl['add']) : ?>
                    <a href="<?php echo $this->url(array('controller' => 'trigger', 'action' => 'add', 'key' => $this->trigger->getKey()), 'ot', true); ?>" class="btn btn-success"><i class="icon-white icon-plus"></i> <?php echo $this->translate("ot-trigger-details:linkAdd"); ?></a>
                <?php endif; ?>
            </p>
        </div>
    </div>   
    <div class="span8">
               
        <?php if (count($this->actions) > 0) : ?>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th width="200"><?php echo $this->translate("ot-trigger-details:name"); ?></th>
                    <th width="300"><?php echo $this->translate("ot-trigger-details:action"); ?></th>
                    <?php if ($this->acl['edit']) : ?>
                    <th width="50"><?php echo $this->translate("table-header-edit"); ?></th>
                    <?php endif; ?>
                    <?php if ($this->acl['delete']) : ?>
                    <th width="50"><?php echo $this->translate("table-header-delete"); ?></th>
                    <?php endif; ?>
                    <?php if ($this->acl['changeStatus']) : ?>
                    <th width="100"><?php echo $this->translate("table-header-status"); ?></th>
                    <?php endif; ?>
                    <?php if ($this->acl['add']) : ?>
                    <th width="100"><?php echo $this->translate("table-header-clone"); ?></th>
                    <?php endif; ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->actions as $a) : ?>
                    <tr>
                        <td><?php echo $a['name']; ?></td>
                        <td><?php echo $a['helper']->getDescription(); ?></td>
                        <?php if ($this->acl['edit']) : ?>
                        <td align="center">
                            <a href="<?php echo $this->url(array('controller' => 'trigger', 'action' => 'edit', 'triggerActionId' => $a['triggerActionId']), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButtonNoText">&nbsp;<span class="ui-icon ui-icon-pencil"></span></a>
                        </td>
                        <?php endif; ?>
                        <?php if ($this->acl['delete']) : ?>
                        <td align="center">
                            <a href="<?php echo $this->url(array('controller' => 'trigger', 'action' => 'delete', 'triggerActionId' => $a['triggerActionId']), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButtonNoText">&nbsp;<span class="ui-icon ui-icon-minusthick"></span></a>
                        </td>
                        <?php endif; ?>
                        <?php if ($this->acl['changeStatus']) : ?>
                        <td align="center">
                            <a href="<?php echo $this->url(array('controller' => 'trigger', 'action' => 'change-status', 'triggerActionId' => $a['triggerActionId']), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButtonNoIcon"><?php echo ($a['enabled']) ? $this->translate('ot-trigger-details:disableAction') : $this->translate('ot-trigger-details:enableAction'); ?></a>
                        </td>
                        <?php endif; ?>
                        <?php if ($this->acl['add']) : ?>
                        <td align="center">
                            <a href="<?php echo $this->url(array('controller' => 'trigger', 'action' => 'add', 'triggerId' => $this->trigger->getName(), 'triggerActionId' => $a['triggerActionId']), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButtonNoIcon"><?php echo $this->translate('ot-trigger-clone:cloneAction'); ?></a>
                        </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>        
        <?php else : ?>
            <?php echo $this->translate("ot-trigger-details:noActions"); ?>                
        <?php endif; ?>
    </div> 
</div>        

<br /><br />