<?php echo $this->translate("ot-trigger-index:header"); ?>
<br /><br />
<table class="table table-bordered table-striped">
    <tbody>
        <tr class="ui-widget-header">
            <th width="250"><?php echo $this->translate("ot-trigger-index:name"); ?></th>
            <th width="350"><?php echo $this->translate("ot-trigger-table:description"); ?></th>
        </tr>
        <?php foreach($this->triggers as $t): ?>
        <tr>
            <td>
                <?php if ($this->acl['details']):?>
                <a href="<?php echo $this->url(array('controller' => 'trigger', 'action' => 'details', 'key' => $t->getKey()), 'ot', true); ?>">
                <?php endif; ?>
                <?php echo $t->getName(); ?>
                <?php if ($this->acl['details']):?>
                </a>
                <?php endif; ?>
            </td>
            <td><?php echo $t->getDescription(); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>