<?php
$nav = new Nav($this->navigation()->getAcl(), $this->navigation()->getRole());

echo $nav->html($this->container);

class Nav
{
    protected $_acl;
    
    protected $_role;
    
    public function __construct(Zend_Acl $acl, $role)
    {
        $this->_acl = $acl;
        $this->_role = $role;
    }
            
    public function html(Zend_Navigation_Container $container)
    {        
        $html = array('<ul class="nav">');
        
        foreach ($container as $page) {
            // visibility of the page
            if (!$page->isVisible()) {
                continue;
            }

            if (!$this->_acl->isAllowed($this->_role, $page->resource, $page->privilege)) {
               continue;
            }

            // dropdown
            $dropdown = !empty($page->pages);

            // header
            $html[] = '<li' . ($dropdown ? ' class="dropdown"' : '') . '>';

            if (!$dropdown) {
                $html[] = '<a href="' . $page->getHref() . '">';
            } else {
                $html[] = '<a href="#" class="dropdown-toggle" data-toggle="dropdown">';
            }

            $html[] = $page->getLabel();

            if ($dropdown) {
                $html[] = '<b class="caret"></b>';
            }

            $html[] = '</a>';

            if (!$dropdown) {
                $html[] = '</li>';
                continue;
            }

            $html[] = '<ul class="dropdown-menu">';

            foreach ($page->pages as $subpage) {
                // visibility of the sub-page
                if (!$subpage->isVisible()) {
                    continue;
                }

                if (!$this->_acl->isAllowed($this->_role, $subpage->resource, $subpage->privilege)) {
                    continue;
                }

                $li = '<li';

                if (!empty($subpage->pages)) {
                    $li .= ' class="dropdown-submenu"';
                }

                $li .= '>';

                $html[] = $li;

                if (!empty($subpage->pages)) {
                    $html[] = '<a href="#">';
                } else {
                    $html[] = '<a href="' . $subpage->getHref() . '">';
                }

                if ($subpage->get('icon')) {
                    $html[] = '<i class="icon-' . $subpage->get('icon') . '"></i>';
                }

                $html[] = $subpage->getLabel();
                $html[] = "</a>";

                if (!empty($subpage->pages)) {
                    $html = array_merge($html, $this->_submenu($subpage));
                }

                $html[] = "</li>";
            }

            $html[] = "</ul>";
            $html[] = "</li>";
        }

        $html[] = '</ul>';

        return join(PHP_EOL, $html);
    }
    
    protected function _submenu($page) 
    {
        $html = array();

        $html[] = '<ul class="dropdown-menu">';

        foreach ($page->pages as $p) {

            // visibility of the sub-page
            if (!$p->isVisible()) {
                continue;
            }


            if (!$this->_acl->isAllowed($this->_role, $p->resource, $p->privilege)) {
                continue;
            }

            $li = '<li';

            if (!empty($p->pages)) {
                $li .= ' class="dropdown-submenu"';
            }

            $li .= '>';

            $html[] = $li;

            if (!empty($p->pages)) {
                $html[] = '<a href="#">';
            } else {
                $html[] = '<a href="' . $p->getHref() . '">';
            }

            if ($p->get('icon')) {
                $html[] = '<i class="icon-' . $p->get('icon') . '"></i>';
            }

            $html[] = $p->getLabel();
            $html[] = "</a>";

            if (!empty($p->pages)) {
                $html = array_merge($html, $this->_submenu($p));
            }

            $html[] = "</li>";        
        }

        $html[] = '</ul>';

        return $html;
    }    
}