<?php if (!$this->guestHasAccess && $this->role['roleId'] == $this->defaultRole->roleId) : ?>
    <div class="alert alert-warning">
        <?php echo $this->translate('ot-acl-details:defaultRoleNeedsAccess', $this->defaultRole->name); ?>
    </div>
<?php endif; ?>

<div class="row">
    <div class="span12">
        <?php echo $this->translate('ot-acl-details:header', $this->role['name']); ?>
        <Br /><br />
    </div>
</div>
<div class="row">
    <div class="span4">
        <div class="thumbnail">

        <table class="form">
            <tbody>
                <tr>
                    <td><label><?php echo $this->translate('model-role-form:roleName'); ?></label></td>
                    <td><?php echo $this->role['name']; ?></td>
                </tr>
                <tr>
                    <td><label><?php echo $this->translate('model-role-form:inheritRoleId'); ?></label></td>
                    <td><?php echo ($this->role['inheritRoleId'] != 0) ? $this->inheritRole : $this->translate('ot-acl-form:noInheritance'); ?></td>
                </tr>
                <tr>
                    <td><label><?php echo $this->translate('ot-acl-details:editable') ?></label></td>
                    <td><?php echo ($this->role['editable'] == 1) ? $this->translate('form-button-yes') : $this->translate('form-button-no'); ?></td>
                </tr>
            </tbody>
        </table>

        <p style="text-align: center">
        <?php if ($this->acl['edit'] && $this->role['editable']): ?>
            <a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'edit', 'roleId' => $this->role['roleId']), 'ot', true); ?>" class="btn"><i class="icon icon-pencil"></i> <?php echo $this->translate('ot-acl-details:edit'); ?></a>
        <?php endif; ?>
        <?php if ($this->acl['delete'] && $this->role['editable'] && $this->role['roleId'] != $this->defaultRole->roleId): ?>
            <a href="#deleteRole" class="btn btn-danger" data-toggle="modal"><i class="icon-white icon-ban-circle"></i> <?php echo $this->translate('ot-acl-details:delete'); ?></a>
            <div id="deleteRole" class="modal hide fade">
                <div class="modal-header">
                    <a class="close" data-dismiss="modal" class="close" href="#">&times;</a>
                    <h3>Delete Role <?php echo $this->role['name']; ?></h3>
                </div>
                <div class="modal-body">
                    <p><?php echo $this->translate('ot-acl-delete:header', $this->role['name']); ?></p>
                    <br />
                    <p><?php echo $this->translate('form-delete-confirm'); ?></p>
                </div>
                <div class="modal-footer">
                    <form style="margin: 0;" method="post" action="<?php echo $this->url(array('controller' => 'acl', 'action' => 'delete'), 'ot', true); ?>">
                        <input type="hidden" name="roleId" value="<?php echo $this->role['roleId']; ?>" />
                        <input type="submit" name="submit" value="Yes, Delete" class="btn btn-danger" />
                        <input type="button" name="cancel" value="Cancel" class="btn" data-dismiss="modal" />
                    </form>
                </div>
            </div>
        <?php endif; ?>
        </p>
        </div>
    </div>
    <div class="span8">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tabs-application" data-toggle="tab"><?php echo $this->translate('ot-acl-index:table:applicationAccess'); ?></a></li>
            <li><a href="#tabs-remote" data-toggle="tab"><?php echo $this->translate('ot-acl-index:table:remoteAccess'); ?></a></li>
        </ul>

        <div class="tab-content">
            <div id="tabs-application" class="tab-pane active">
                <form method="post" id="aclEditor" action="" class="checkRequiredFields">
        <?php if (count($this->children) != 0) : ?>
        <div class="ui-state-highlight ui-corner-all">
            <span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
            <?php echo $this->translate('ot-acl-applicationAccess:caution'); ?>
            <ul>
            <?php foreach ($this->children as $c) : ?>
                <li>
                <a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'details', 'roleId' => $c['roleId']), 'ot', true); ?>"><?php echo $c['name']; ?></a> <?php echo $this->translate('ot-acl-applicationAccess:via'); ?>
                <a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'details', 'roleId' => $c['parent']['roleId']), 'ot', true); ?>"><?php echo $c['parent']['name']; ?></a>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>
        <div id="accessList">
            <?php foreach ($this->resources as $module => $controllers) : ?>
            <div class="aclSection">
                <table class="table table-bordered table-condensed">
                    <thead>
                    <tr>
                        <th width="300"><?php echo ucwords($module); ?></th>
                        <th width="120"><?php echo $this->translate('ot-acl-form:currently'); ?></th>
                        <th width="180"><?php echo $this->translate('ot-acl-form:grantRevoke'); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($controllers as $controller => $actions) : ?>
                    <tr class="controller <?php if (!empty($actions['all']['access'])) { echo 'success'; } else { if (!empty($actions['someaccess'])) { echo 'warning'; } else { echo 'error'; }} ?>">
                        <td title="<?php echo $actions['description']; ?>" class="td1 description">
                        <?php echo ucwords($controller); ?>
                        </td>
                        <td>
                        <?php if (!empty($actions['all']['access'])) : ?>
                            <?php echo $this->translate('ot-acl-form:allAccess'); ?>
                        <?php else: ?>
                            <?php if (isset($actions['someaccess'])) : ?>
                            <?php echo $this->translate('ot-acl-form:someAccess'); ?>
                            <?php else: ?>
                            <?php echo $this->translate('ot-acl-form:noAccess'); ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        </td>
                        <td>
                        <select size="1" class="allAccess" name="<?php echo $module . '[' . $controller . '][all]'; ?>" id="<?php echo $module . '_' . $controller; ?>">
                            <option value="<?php if (!empty($actions['all']['access'])) { echo 'allow'; } else { if (!empty($actions['someaccess'])) { echo 'some'; } else { echo 'deny'; }} ?>"><?php echo $this->translate('ot-acl-form:noChange'); ?></option>
                        <?php if (empty($actions['all']['access'])) : ?>
                            <option value="allow"><?php echo $this->translate('ot-acl-form:grantAllAccess'); ?></option>
                        <?php endif; ?>
                        <?php if (empty($actions['someaccess']) || !empty($actions['all']['access'])) : ?>
                            <option value="some"><?php echo (empty($actions['all']['access'])) ? $this->translate('ot-acl-form:grant') : $this->translate('ot-acl-form:revoke'); ?> <?php echo $this->translate('ot-acl-form:someAccess'); ?></option>
                        <?php endif; ?>
                        <?php if (!empty($actions['all']['access']) || !empty($actions['someaccess'])) : ?>
                            <option value="deny"><?php echo $this->translate('ot-acl-form:revokeAllAccess'); ?></option>
                        <?php endif; ?>
                        </select>
                        </td>
                    </tr>
                    <?php if (isset($actions['part'])): ?>
                        <?php foreach ($actions['part'] as $action => $access) : ?>
                    <tr class="action <?php echo $module . '_' . $controller; ?>" style="display: <?php echo (empty($actions['someaccess']) || !empty($actions['all']['access'])) ? 'none' : ''; ?>;">
                        <td class="td1 description" title="<?php echo $access['description']; ?>">
                        <?php echo ucwords($action); ?>
                        </td>
                        <td class="<?php echo (!empty($access['access'])) ? 'access' : 'noAccess'; ?>"><?php echo (!empty($access['access'])) ? $this->translate('ot-acl-form:hasAccess') : $this->translate('ot-acl-form:noAccess'); ?></td>
                        <td class="td3"><label><input type="checkbox" class="<?php echo $module . '_' . $controller; ?>_action" value="<?php echo (!empty($access['access'])) ? 'deny' : 'allow'; ?>" name="<?php echo $module . '[' . $controller . '][part][' . $action . ']'; ?>" id="<?php echo $module . '_' . $controller . '_part_' . $action; ?>" /> <?php echo (!empty($access['access'])) ? $this->translate('ot-acl-form:revokeAccess') : $this->translate('ot-acl-form:grantAccess'); ?></label></td>
                    </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php endforeach; ?>
            <input type="submit" value="<?php echo $this->translate('model-role-form:submit'); ?>" />
            <button type="button" id="cancel"><?php echo $this->translate('form-button-cancel'); ?></button>
        </div>

    </form>
            </div>
            <div id="tabs-remote" class="tab-pane">
                <?php if ($this->acl['remote-access'] && $this->role['editable']): ?>
                    <a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'remote-access', 'roleId' => $this->role['roleId']), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton"><?php echo $this->translate('ot-acl-details:remoteAccess:edit'); ?><span class="ui-icon ui-icon-transferthick-e-w"></span></a>
                    <br /><br />
                <?php endif; ?>
                <?php echo $this->translate('ot-acl-details:remoteAccess:header'); ?>
                <br /><br />
                <div class="accessTable">
                <?php foreach ($this->remoteResources as $module => $controllers) : ?>
                <div class="aclSection">
                    <table class="list">
                        <tbody>
                        <tr class="ui-widget-header">
                            <td width="300"><b><?php echo ucwords($module); ?></b></td>
                            <td width="120"><?php echo $this->translate('ot-acl-details:form:access'); ?></td>
                        </tr>
                        <?php foreach ($controllers as $controller => $actions) : ?>
                        <tr class="controller">
                            <td title="<?php echo $actions['description']; ?>" class="td1 description">
                            <?php echo ucwords($controller); ?>
                            </td>
                            <td class="<?php if (!empty($actions['all']['access'])) { echo 'access'; } else { if (!empty($actions['someaccess'])) { echo 'someAccess'; } else { echo 'noAccess'; }} ?>">
                            <?php if (!empty($actions['all']['access'])) : ?>
                                <?php echo $this->translate('ot-acl-form:allAccess'); ?>
                            <?php else: ?>
                                <?php if (isset($actions['someaccess'])) : ?>
                                <?php echo $this->translate('ot-acl-form:someAccess'); ?>
                                <?php else: ?>
                                <?php echo $this->translate('ot-acl-form:noAccess'); ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            </td>
                        </tr>
                        <?php if (isset($actions['part'])): ?>
                            <?php foreach ($actions['part'] as $action => $access) : ?>
                        <tr class="action <?php echo $module . '_' . $controller; ?>" style="display: <?php echo (empty($actions['someaccess']) || !empty($actions['all']['access'])) ? 'none' : ''; ?>;">
                            <td class="td1 description" title="<?php echo $access['description']; ?>">
                            <img src="<?php echo $this->baseUrl(); ?>/images/ot/help.png" width="16" height="16" class="info" />
                            <?php echo ucwords($action); ?>
                            </td>
                            <td class="<?php echo (!empty($access['access'])) ? 'access' : 'noAccess'; ?>"><?php echo (!empty($access['access'])) ? $this->translate('ot-acl-form:hasAccess') : $this->translate('ot-acl-form:noAccess'); ?></td>
                        </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php if (!$this->acl['index']): ?>
    <a href="<?php echo $this->url(array('controller' => 'acl'), 'ot', true); ?>" class="btn"><i class="icon icon-arrow-left"></i> <?php echo $this->translate('ot-acl-details:back'); ?></a>
    <br /><br />
<?php endif; ?>



