<?php if (!$this->guestHasAccess) : ?>
    <div class="alert alert-warning">
        <?php echo $this->translate('ot-acl-index:defaultRoleNeedsAccess', $this->defaultRole->name); ?>
    </div>
<?php endif; ?>

<?php echo $this->translate('ot-acl-index:header'); ?>
<br /><br />

<?php if ($this->acl['add']): ?>
<a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'add'), 'ot', true); ?>" class="btn btn-success"><i class="icon-white icon-plus"></i> <?php echo $this->translate('ot-acl-index:linkAdd'); ?></a>
<br /><br />
<?php endif; ?>


<?php if (count($this->roles) > 0): ?>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th width="200"><?php echo $this->translate('ot-acl-index:table:roleName'); ?></th>
            <th width="200"><?php echo $this->translate('ot-acl-index:table:inheritedFrom'); ?></th>
            <?php if ($this->acl['application-access']): ?>
            <th width="120"><?php echo $this->translate('ot-acl-index:table:applicationAccess'); ?></th>
            <?php endif; ?>
            <?php if ($this->acl['remote-access']): ?>
            <th width="120"><?php echo $this->translate('ot-acl-index:table:remoteAccess'); ?></th>
            <?php endif; ?>
            <?php if ($this->acl['edit']): ?>
            <th width="50"><?php echo $this->translate('table-header-edit'); ?></th>
            <?php endif; ?>
            <?php if ($this->acl['delete']): ?>
            <th width="50"><?php echo $this->translate('table-header-delete'); ?></th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->roles as $r) : ?>
    <tr>
        <td><a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'details', 'roleId' => $r['roleId']), 'ot', true); ?>"><?php echo $r['name']; ?></a></td>
        <td style="text-align:center"><?php if ($r['inheritRoleId'] != 0) { echo $this->roles[$r['inheritRoleId']]['name']; } else { echo $this->translate("ot-acl-form:noInheritance"); } ?></td>
        <?php if ($this->acl['application-access']): ?>
        <td style="text-align:center">
            <?php if ($r['editable']): ?>
            <a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'application-access', 'roleId' => $r['roleId']), 'ot', true); ?>" class="btn btn-info"><i class="icon-white icon-th-list"></i></a>
            <?php else: ?>
            <a class="btn disabled"><i class="icon icon-lock"></i></a>
            <?php endif; ?>
        </td>
        <?php endif; ?>
        <?php if ($this->acl['remote-access']): ?>
        <td style="text-align:center">
            <?php if ($r['editable']): ?>
            <a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'remote-access', 'roleId' => $r['roleId']), 'ot', true); ?>" class="btn btn-info"><i class="icon-white icon-random"></i></a>
            <?php else: ?>
            <a class="btn disabled"><i class="icon icon-lock"></i></a>
            <?php endif; ?>
        </td>
        <?php endif; ?>
        <?php if ($this->acl['edit']): ?>
        <td style="text-align:center">
            <?php if ($r['editable']): ?>
            <a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'edit', 'roleId' => $r['roleId']), 'ot', true); ?>" class="btn btn-info"><i class="icon-white icon-pencil"></i></a>
            <?php else: ?>
            <a class="btn disabled"><i class="icon icon-lock"></i></a>
            <?php endif; ?>
        </td>
        <?php endif; ?>
        <?php if ($this->acl['delete']): ?>
        <td style="text-align:center">
            <?php if ($r['editable']): ?>
                <?php if ($r['inheritedFrom']): ?>
                    <a class="btn disabled"><i class="icon icon-lock"></i></a>
                <?php else: ?>
                    <a href="<?php echo $this->url(array('controller' => 'acl', 'action' => 'delete', 'roleId' => $r['roleId']), 'ot', true); ?>" class="btn btn-danger"><i class="icon-white icon-ban-circle"></i></a>
                <?php endif; ?>
            <?php else: ?>
                <a class="btn disabled"><i class="icon icon-lock"></i></a>
            <?php endif; ?>
        </td>
        <?php endif; ?>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<div class="noItems">
    <?php echo $this->translate('ot-acl-index:noRoles'); ?>
</div>
<?php endif; ?>