<div id="translationInstructions">
You may change any of the text on this page by including text in the <b>Change Text To:</b> block.  If you wish to remove
an existing text change and reset it back to the default text, check the box marked <b>Remove custom text and reset to default</b>.  When you
are done, click <b>Save</b> to save your changes.
</div>
<?php if (count($this->translationTable) != 0): ?>
<form method="post" id="translationForm" action="<?php echo $this->baseUrl(); ?>/admin/translate/index/?module=<?php echo $this->module; ?>&controller=<?php echo $this->controller; ?>&action=<?php echo $this->action; ?>">
	<div id="translateKeys">
	  	<?php foreach ($this->translationTable as $key => $value): ?>
			<div>
				<h3><a href='#'>Section: <?php echo $value['title']; ?></a></h3>
				<div>
				<label for="<?php echo $key; ?>_old"><b>Current Text is:</b></label><br />
				<textarea readonly="1" id="<?php echo $key; ?>_old" style="width:400px"><?php echo htmlentities($value['value']); ?></textarea>
				<br /><br />
				<label for="<?php echo $key; ?>_new"><b>Change Text to: </b>(leave blank for no changes)</label><br />
				<textarea style="width:400px" name="<?php echo $key; ?>" id="<?php echo $key; ?>_new"></textarea>
				<br /><br />
				<input type="checkbox" value="ON" name="<?php echo $key; ?>#reset" /> Remove custom text and reset to default<br />
				</div>
			</div>
		<?php endforeach; ?>
	</div>
	<?php if ($this->showSubmit): ?>
	<input type="submit" value="Submit" />
	<?php endif; ?>
</form>	
<?php else: ?>
<div class="ui-state-error ui-corner-all">
<span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"/>
No text can be changed on this page.</div>
<?php endif; ?>