<?php if ($this->acl['index']): ?>
<a href="<?php echo $this->baseUrl(); ?>/admin/trigger/" class="ui-state-default ui-corner-all linkButton">Back to Trigger List<span class="ui-icon ui-icon-triangle-1-w"></span></a><br /><br />
<?php endif; ?>

You can manage the actions for this trigger here.

<br /><br />
<table class="form">
    <tbody>
        <tr>
            <td><label>Trigger:</label></td>
            <td><?php echo $this->triggerId; ?></td>
        </tr>
        <tr>
            <td><label>Description:</label></td>
            <td><?php echo $this->trigger->description; ?></td>
        </tr>
    </tbody>
</table><br />
    <?php if ($this->acl['add']) : ?>
    <a href="<?php echo $this->baseUrl(); ?>/admin/trigger/add/?triggerId=<?php echo $this->triggerId; ?>" class="ui-state-default ui-corner-all linkButton">Add New Action<span class="ui-icon ui-icon-plusthick"></span></a>
    <br /><br />
    <?php endif; ?>
    
    <table class="list">
        <tbody>
            <tr class="ui-widget-header">
                <th width="200">Name</th>
                <th width="300">Action</th>
                <?php if ($this->acl['edit']) : ?>
                <th width="50">Edit</th>
                <?php endif; ?>
                <?php if ($this->acl['delete']) : ?>
                <th width="50">Delete</th>
                <?php endif; ?>
            </tr>
            <?php if (count($this->actions) > 0) : ?>
                <?php foreach ($this->actions as $a) : ?>
                <tr>
                    <td><?php echo $a['name']; ?></td>
                    <td><?php echo $a['helper']; ?></td>
                    <?php if ($this->acl['edit']) : ?>
                    <td align="center">
                        <a href="<?php echo $this->baseUrl(); ?>/admin/trigger/edit/?triggerActionId=<?php echo $a['triggerActionId']; ?>" class="ui-state-default ui-corner-all linkButtonNoText"><span class="ui-icon ui-icon-pencil"></span></a>
                    </td>
                    <?php endif; ?>
                    <?php if ($this->acl['delete']) : ?>
                    <td align="center">
                        <a href="<?php echo $this->baseUrl(); ?>/admin/trigger/delete/?triggerActionId=<?php echo $a['triggerActionId']; ?>" class="ui-state-default ui-corner-all linkButtonNoText"><span class="ui-icon ui-icon-minusthick"></span></a>
                    </td>
                    <?php endif; ?>
                </tr>
                <?php endforeach; ?>
            <?php else : ?>
                <tr>
                    <td class="noResults" colspan="4">No Actions Found</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>