<div id="footer" align="center">
    <div class="floatLeft">
        <a href="http://framework.zend.com" target="_blank"><img align="left" src="<?php echo $this->baseUrl(); ?>/public/ot/images/PoweredBy_ZF_4LightBG.png" width="127" height="25" alt="Powered By Zend Framework" /></a>            
    </div>
    <div class="floatRight">
        <a href="http://webapps.ncsu.edu/"><img src="<?php echo $this->baseUrl(); ?>/public/ot/images/minilogo.png" width="128" height="21" alt="OIT - Outreach Technologies" /></a>
    </div>
    <a href="<?php echo $this->baseUrl(); ?>/admin/bug/add/">Report a Bug</a>
    &nbsp;&nbsp;&copy; <?php echo date('Y'); ?> North Carolina State University
</div>