<div id="footer" align="center">
    <div class="floatLeft">
        <a href="http://framework.zend.com" target="_blank"><img align="left" src="<?php echo $this->themeBaseUrl(); ?>/public/images/PoweredBy_ZF_4LightBG.png" width="127" height="25" alt="<?php echo $this->translate('theme-scripts-footer:poweredByZendFramework'); ?>" /></a>            
    </div>
    <div class="floatRight">
        <a href="http://webapps.ncsu.edu/"><img src="<?php echo $this->themeBaseUrl(); ?>/public/images/minilogo.png" width="128" height="21" alt="<?php echo $this->translate('theme-scripts-footer:OIT'); ?>" /></a>
    </div>
    &nbsp;&nbsp;&copy; <?php echo date('Y'); ?> <?php echo $this->translate('theme-scripts-footer:NCSU'); ?>
</div>