<?php echo $this->translate("admin-index-index:header"); ?>
<br /><br />
<b><?php echo $this->translate("admin-index-index:ot"); ?></b> <?php echo $this->otVersion; ?><br /><br />
<b><?php echo $this->translate("admin-index-index:zend"); ?></b> <?php echo $this->zfVersion; ?><br /><br />
<b><?php echo $this->translate("admin-index-index:jQuery"); ?></b> <span id="jQueryVersion"></span><br /><br />
<b><?php echo $this->translate("admin-index-index:jQueryUi"); ?></b> <span id="jQueryUiVersion"></span><br /><br />