<table class="form">
    <tbody>
        <tr>
            <td width="100"><label><?php echo $this->translate("ot-custom-form:object"); ?></label></td>
            <td><?php echo $this->objectId; ?></td>
        </tr>
        <tr>
            <td><label><?php echo $this->translate("ot-custom-form:description"); ?></label></td>
            <td><?php echo $this->objectDescription; ?></td>
        </tr>
    </tbody>
</table>
<br /><br />
<?php echo $this->translate("ot-custom-delete:header", array($this->attribute['label'])); ?>
<?php echo $this->form; ?>