<?php
        
$html = array('<div class="dd" id="navList">');
$html[] = '  <ol class="dd-list">';
 
$html = array_merge($html, editSubmenu($this->container, 0));     
 
$html[] = '  </ol>';
$html[] = '</div>';
 
echo join(PHP_EOL, $html);

function editSubmenu($pages, $parentId)
{
    $html = array();
    
    foreach ($pages as $p) {
        
        $html[] = '    <li class="dd-item" data-id="' . $p->getId() . '" name="' . $p->getLabel() . '" id="navItem_' . $parentId . '_' . $p->getId() . '">';
    
        $html[] = '        <div class="dd-handle dd3-handle">Drag</div><div class="dd3-content">';
        
        $resource = explode('_', $p->getResource());
        $privilege = $p->getPrivilege();
        
        $module = $resource[0];
        $controller = $resource[1];
        $action = $privilege;
        
        $html[] = '            <a class="link" target="' . $p->getTarget() . '" title="' . $module . ':' . $controller . ':' . $action . '" href="' . $p->getHref() . '">' . $p->getLabel() . '</a>';
        $html[] = '            <a class="btn btn-mini btn-danger controlButton deleteElement" title="Delete"><i class="icon-white icon-minus"></i></a>';
        $html[] = '            <a class="btn btn-mini controlButton editElement" title="Edit"><i class="icon icon-pencil"></i></a>';
        
        $html[] = '        </div>';
        
        if (!empty($p->pages)) {
                
            $html[] = '        <ol class="dd-list">';
            
            $html = array_merge($html, editSubmenu($p->pages, $p->getId()));            
    
            $html[] = '        </ol>';
        }
        
        $html[] = "    </li>"; 
    }
    
    return $html;
}