<?php
        
$html = array('<ul id="masterList">');
 
$html = array_merge($html, editSubmenu($this->container, 0));     
 
$html[] = '</ul>';
 
echo join(PHP_EOL, $html);

function editSubmenu($pages, $parentId) 
{
    $html = array();
    
    foreach ($pages as $p) {
        
        $html[] = '<li name="' . $p->getLabel() . '" id="navItem_' . $parentId . '_' . $p->getId() . '">';
                
        $html[] = '<div class="dropzone"></div>';
        
        $html[] = '<i class="icon icon-resize-vertical"></i>';
    
        $resource = explode('_', $p->getResource());
        $privilege = $p->getPrivilege();
        
        $module = $resource[0];
        $controller = $resource[1];
        $action = $privilege;
        
        $html[] = '<a target="' . $p->getTarget() . '" title="' . $module . ':' . $controller . ':' . $action . '" href="' . $p->getHref() . '">';
     
        $html[] = $p->getLabel();

        $html[] = '</a>';
        
        $html[] = '<a class="btn btn-danger controlButton deleteElement" title="Delete"><i class="icon-white icon-minus"></i></a>';
    
        $html[] = '<a class="btn controlButton editElement" title="Edit"><i class="icon icon-pencil"></i></a>';    
        
        
        if (!empty($p->pages)) {
                
            $html[] = '<ul>';
            
            $html = array_merge($html, editSubmenu($p->pages, $p->getId()));            
    
            $html[] = '</ul>';
        }
        
        $html[] = "</li>";        
    }
    
    return $html;
}