<?php echo $this->translate("ot-auth-index:header"); ?>
<br /><br />

<div id="message">
    <div id="orderMessage" class="ui-widget ui-state-highlight ui-corner-all"></div>    
</div>

<?php if (count($this->adapters) != 0): ?>
<ul id="adapterList" class="ui-sortable">
    <?php foreach ($this->adapters as $a): ?>
        <li id="attribute_<?php echo $a->adapterKey; ?>" class="adapter">         
            <div class="status <?php echo ($a->enabled) ? 'enabled' : 'disabled'; ?>"></div>
            <div class="actions">
                <?php if ($a->enabled): ?>
                    <?php if ($this->numEnabledAdapters > 1 && $this->acl['toggle']): ?>
                        <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'toggle', 'key' => $a->adapterKey), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton">&nbsp;<span class="ui-icon ui-icon-minusthick"></span><?php echo $this->translate('ot-auth-index:disable'); ?></a>
                    <?php endif; ?>
                <?php else: ?>
                    <?php if ($this->acl['toggle']) : ?>
                        <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'toggle', 'key' => $a->adapterKey), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton">&nbsp;<span class="ui-icon ui-icon-plusthick"></span><?php echo $this->translate('ot-auth-index:enable'); ?></a>
                    <?php endif; ?>
                <?php endif; ?>                        
                <?php if ($this->acl['edit']): ?>
                    <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'edit', 'key' => $a->adapterKey), 'ot', true); ?>" class="ui-state-default ui-corner-all linkButton">&nbsp;<span class="ui-icon ui-icon-pencil"></span>Edit</a>
                <?php endif;?>                    
            </div>
            <div class="name">
                <span class="ui-icon ui-icon-arrowthick-2-n-s dragIndicator">&nbsp;</span><?php echo $a->name; ?>
            </div>
            <div class="description"><?php echo $a->description; ?></div>            
            <div class="ui-helper-clearfix"></div>
        </li>
    <?php endforeach; ?>
</ul>
<?php else: ?>
<h3>No Auth Adapters Found</h3>
<?php endif; ?>
